{
//=========Macro generated from canvas: DataGenLOverMCGenL/DataGenLOverMCGenL
//=========  (Wed Aug 17 12:58:51 2016) by ROOT version5.34/30
   TCanvas *DataGenLOverMCGenL = new TCanvas("DataGenLOverMCGenL", "DataGenLOverMCGenL",50,72,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   DataGenLOverMCGenL->Range(2.659429,-0.335,6.76419,3.29);
   DataGenLOverMCGenL->SetFillColor(0);
   DataGenLOverMCGenL->SetBorderMode(0);
   DataGenLOverMCGenL->SetBorderSize(2);
   DataGenLOverMCGenL->SetTickx(1);
   DataGenLOverMCGenL->SetTicky(1);
   DataGenLOverMCGenL->SetLeftMargin(0.12);
   DataGenLOverMCGenL->SetRightMargin(0.04);
   DataGenLOverMCGenL->SetTopMargin(0.08);
   DataGenLOverMCGenL->SetBottomMargin(0.12);
   DataGenLOverMCGenL->SetFrameFillStyle(0);
   DataGenLOverMCGenL->SetFrameBorderMode(0);
   DataGenLOverMCGenL->SetFrameFillStyle(0);
   DataGenLOverMCGenL->SetFrameBorderMode(0);
   Double_t xAxis1[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataGenLOverpythia8_MonashGenL = new TH1F("DataGenLOverpythia8_MonashGenL","DataGenLOverpythia8_MonashGenL",7, xAxis1);
   DataGenLOverpythia8_MonashGenL->SetBinContent(1,0.6054683);
   DataGenLOverpythia8_MonashGenL->SetBinContent(2,0.5462275);
   DataGenLOverpythia8_MonashGenL->SetBinContent(3,0.5225603);
   DataGenLOverpythia8_MonashGenL->SetBinContent(4,0.532962);
   DataGenLOverpythia8_MonashGenL->SetBinContent(5,0.4425531);
   DataGenLOverpythia8_MonashGenL->SetBinContent(6,0.6030435);
   DataGenLOverpythia8_MonashGenL->SetBinContent(7,0.8972481);
   DataGenLOverpythia8_MonashGenL->SetBinError(1,0.02451766);
   DataGenLOverpythia8_MonashGenL->SetBinError(2,0.01364319);
   DataGenLOverpythia8_MonashGenL->SetBinError(3,0.007195561);
   DataGenLOverpythia8_MonashGenL->SetBinError(4,0.01131412);
   DataGenLOverpythia8_MonashGenL->SetBinError(5,0.01968496);
   DataGenLOverpythia8_MonashGenL->SetBinError(6,0.02660231);
   DataGenLOverpythia8_MonashGenL->SetBinError(7,0.01567615);
   DataGenLOverpythia8_MonashGenL->SetMinimum(0.1);
   DataGenLOverpythia8_MonashGenL->SetMaximum(3);
   DataGenLOverpythia8_MonashGenL->SetEntries(7);
   DataGenLOverpythia8_MonashGenL->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#990099");
   DataGenLOverpythia8_MonashGenL->SetLineColor(ci);
   DataGenLOverpythia8_MonashGenL->SetLineStyle(2);
   DataGenLOverpythia8_MonashGenL->SetLineWidth(5);

   ci = TColor::GetColor("#990099");
   DataGenLOverpythia8_MonashGenL->SetMarkerColor(ci);
   DataGenLOverpythia8_MonashGenL->SetMarkerStyle(20);
   DataGenLOverpythia8_MonashGenL->GetXaxis()->SetTitle("|#eta|");
   DataGenLOverpythia8_MonashGenL->GetXaxis()->SetLabelFont(42);
   DataGenLOverpythia8_MonashGenL->GetXaxis()->SetLabelOffset(0.007);
   DataGenLOverpythia8_MonashGenL->GetXaxis()->SetLabelSize(0.05);
   DataGenLOverpythia8_MonashGenL->GetXaxis()->SetTitleSize(0.05);
   DataGenLOverpythia8_MonashGenL->GetXaxis()->SetTitleOffset(0.9);
   DataGenLOverpythia8_MonashGenL->GetXaxis()->SetTitleFont(42);
   DataGenLOverpythia8_MonashGenL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataGenLOverpythia8_MonashGenL->GetYaxis()->SetLabelFont(42);
   DataGenLOverpythia8_MonashGenL->GetYaxis()->SetLabelOffset(0.007);
   DataGenLOverpythia8_MonashGenL->GetYaxis()->SetLabelSize(0.05);
   DataGenLOverpythia8_MonashGenL->GetYaxis()->SetTitleSize(0.05);
   DataGenLOverpythia8_MonashGenL->GetYaxis()->SetTitleFont(42);
   DataGenLOverpythia8_MonashGenL->GetZaxis()->SetLabelFont(42);
   DataGenLOverpythia8_MonashGenL->GetZaxis()->SetLabelOffset(0.007);
   DataGenLOverpythia8_MonashGenL->GetZaxis()->SetLabelSize(0.05);
   DataGenLOverpythia8_MonashGenL->GetZaxis()->SetTitleSize(0.05);
   DataGenLOverpythia8_MonashGenL->GetZaxis()->SetTitleFont(42);
   DataGenLOverpythia8_MonashGenL->Draw("AXIS");
   TLatex *   tex = new TLatex(0.96,0.936,"0.06 nb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.892,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.82,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis2[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataGenLOverpythia8_MonashGenL__1 = new TH1F("DataGenLOverpythia8_MonashGenL__1","DataGenLOverpythia8_MonashGenL",7, xAxis2);
   DataGenLOverpythia8_MonashGenL__1->SetBinContent(1,0.6054683);
   DataGenLOverpythia8_MonashGenL__1->SetBinContent(2,0.5462275);
   DataGenLOverpythia8_MonashGenL__1->SetBinContent(3,0.5225603);
   DataGenLOverpythia8_MonashGenL__1->SetBinContent(4,0.532962);
   DataGenLOverpythia8_MonashGenL__1->SetBinContent(5,0.4425531);
   DataGenLOverpythia8_MonashGenL__1->SetBinContent(6,0.6030435);
   DataGenLOverpythia8_MonashGenL__1->SetBinContent(7,0.8972481);
   DataGenLOverpythia8_MonashGenL__1->SetBinError(1,0.02451766);
   DataGenLOverpythia8_MonashGenL__1->SetBinError(2,0.01364319);
   DataGenLOverpythia8_MonashGenL__1->SetBinError(3,0.007195561);
   DataGenLOverpythia8_MonashGenL__1->SetBinError(4,0.01131412);
   DataGenLOverpythia8_MonashGenL__1->SetBinError(5,0.01968496);
   DataGenLOverpythia8_MonashGenL__1->SetBinError(6,0.02660231);
   DataGenLOverpythia8_MonashGenL__1->SetBinError(7,0.01567615);
   DataGenLOverpythia8_MonashGenL__1->SetMinimum(0.1);
   DataGenLOverpythia8_MonashGenL__1->SetMaximum(3);
   DataGenLOverpythia8_MonashGenL__1->SetEntries(7);
   DataGenLOverpythia8_MonashGenL__1->SetDirectory(0);
   DataGenLOverpythia8_MonashGenL__1->SetStats(0);

   ci = TColor::GetColor("#990099");
   DataGenLOverpythia8_MonashGenL__1->SetLineColor(ci);
   DataGenLOverpythia8_MonashGenL__1->SetLineStyle(2);
   DataGenLOverpythia8_MonashGenL__1->SetLineWidth(5);

   ci = TColor::GetColor("#990099");
   DataGenLOverpythia8_MonashGenL__1->SetMarkerColor(ci);
   DataGenLOverpythia8_MonashGenL__1->SetMarkerStyle(20);
   DataGenLOverpythia8_MonashGenL__1->GetXaxis()->SetTitle("|#eta|");
   DataGenLOverpythia8_MonashGenL__1->GetXaxis()->SetLabelFont(42);
   DataGenLOverpythia8_MonashGenL__1->GetXaxis()->SetLabelOffset(0.007);
   DataGenLOverpythia8_MonashGenL__1->GetXaxis()->SetLabelSize(0.05);
   DataGenLOverpythia8_MonashGenL__1->GetXaxis()->SetTitleSize(0.05);
   DataGenLOverpythia8_MonashGenL__1->GetXaxis()->SetTitleOffset(0.9);
   DataGenLOverpythia8_MonashGenL__1->GetXaxis()->SetTitleFont(42);
   DataGenLOverpythia8_MonashGenL__1->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataGenLOverpythia8_MonashGenL__1->GetYaxis()->SetLabelFont(42);
   DataGenLOverpythia8_MonashGenL__1->GetYaxis()->SetLabelOffset(0.007);
   DataGenLOverpythia8_MonashGenL__1->GetYaxis()->SetLabelSize(0.05);
   DataGenLOverpythia8_MonashGenL__1->GetYaxis()->SetTitleSize(0.05);
   DataGenLOverpythia8_MonashGenL__1->GetYaxis()->SetTitleFont(42);
   DataGenLOverpythia8_MonashGenL__1->GetZaxis()->SetLabelFont(42);
   DataGenLOverpythia8_MonashGenL__1->GetZaxis()->SetLabelOffset(0.007);
   DataGenLOverpythia8_MonashGenL__1->GetZaxis()->SetLabelSize(0.05);
   DataGenLOverpythia8_MonashGenL__1->GetZaxis()->SetTitleSize(0.05);
   DataGenLOverpythia8_MonashGenL__1->GetZaxis()->SetTitleFont(42);
   DataGenLOverpythia8_MonashGenL__1->Draw("sameaxis");
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(7);
   grae->SetName("TotalUnc_Ratio");
   grae->SetTitle("Graph");

   ci = TColor::GetColor("#999999");
   grae->SetFillColor(ci);
   grae->SetMarkerStyle(20);
   grae->SetPoint(0,3.3275,1);
   grae->SetPointError(0,0.1755,0.1755,31.51964,31.51964);
   grae->SetPoint(1,3.678,1);
   grae->SetPointError(1,0.175,0.175,46.18525,46.18525);
   grae->SetPoint(2,4.0285,1);
   grae->SetPointError(2,0.1755,0.1755,67.88458,67.88458);
   grae->SetPoint(3,4.378,1);
   grae->SetPointError(3,0.174,0.174,100.9531,100.9531);
   grae->SetPoint(4,4.7275,1);
   grae->SetPointError(4,0.1754999,0.1754999,177.8893,177.8893);
   grae->SetPoint(5,5.054,1);
   grae->SetPointError(5,0.151,0.151,186.876,186.876);
   grae->SetPoint(6,5.9025,1);
   grae->SetPointError(6,0.6975,0.6975,0.2533417,0.2533417);
   
   TH1F *Graph_TotalUnc_Ratio1 = new TH1F("Graph_TotalUnc_Ratio1","Graph",100,2.8072,6.9448);
   Graph_TotalUnc_Ratio1->SetMinimum(-223.2512);
   Graph_TotalUnc_Ratio1->SetMaximum(225.2512);
   Graph_TotalUnc_Ratio1->SetDirectory(0);
   Graph_TotalUnc_Ratio1->SetStats(0);
   Graph_TotalUnc_Ratio1->SetLineStyle(0);
   Graph_TotalUnc_Ratio1->SetMarkerStyle(20);
   Graph_TotalUnc_Ratio1->GetXaxis()->SetLabelFont(42);
   Graph_TotalUnc_Ratio1->GetXaxis()->SetLabelOffset(0.007);
   Graph_TotalUnc_Ratio1->GetXaxis()->SetLabelSize(0.05);
   Graph_TotalUnc_Ratio1->GetXaxis()->SetTitleSize(0.05);
   Graph_TotalUnc_Ratio1->GetXaxis()->SetTitleFont(42);
   Graph_TotalUnc_Ratio1->GetYaxis()->SetLabelFont(42);
   Graph_TotalUnc_Ratio1->GetYaxis()->SetLabelOffset(0.007);
   Graph_TotalUnc_Ratio1->GetYaxis()->SetLabelSize(0.05);
   Graph_TotalUnc_Ratio1->GetYaxis()->SetTitleSize(0.05);
   Graph_TotalUnc_Ratio1->GetYaxis()->SetTitleFont(42);
   Graph_TotalUnc_Ratio1->GetZaxis()->SetLabelFont(42);
   Graph_TotalUnc_Ratio1->GetZaxis()->SetLabelOffset(0.007);
   Graph_TotalUnc_Ratio1->GetZaxis()->SetLabelSize(0.05);
   Graph_TotalUnc_Ratio1->GetZaxis()->SetTitleSize(0.05);
   Graph_TotalUnc_Ratio1->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_TotalUnc_Ratio1);
   
   grae->Draw("2");
   Double_t xAxis3[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataGenLOverDataGenL = new TH1F("DataGenLOverDataGenL","DataGenLOverDataGenL",7, xAxis3);
   DataGenLOverDataGenL->SetBinContent(1,0.4476084);
   DataGenLOverDataGenL->SetBinContent(2,0.3968141);
   DataGenLOverDataGenL->SetBinContent(3,0.3973924);
   DataGenLOverDataGenL->SetBinContent(4,0.4034377);
   DataGenLOverDataGenL->SetBinContent(5,0.3398863);
   DataGenLOverDataGenL->SetBinContent(6,0.4688588);
   DataGenLOverDataGenL->SetBinContent(7,0.6854745);
   DataGenLOverDataGenL->SetBinError(1,0.01388018);
   DataGenLOverDataGenL->SetBinError(2,0.01746497);
   DataGenLOverDataGenL->SetBinError(3,0.01742666);
   DataGenLOverDataGenL->SetBinError(4,0.01797446);
   DataGenLOverDataGenL->SetBinError(5,0.02394288);
   DataGenLOverDataGenL->SetBinError(6,0.01210787);
   DataGenLOverDataGenL->SetBinError(7,0.00940029);
   DataGenLOverDataGenL->SetEntries(7);
   DataGenLOverDataGenL->SetStats(0);

   ci = TColor::GetColor("#006633");
   DataGenLOverDataGenL->SetLineColor(ci);
   DataGenLOverDataGenL->SetLineWidth(5);

   ci = TColor::GetColor("#006633");
   DataGenLOverDataGenL->SetMarkerColor(ci);
   DataGenLOverDataGenL->SetMarkerStyle(20);
   DataGenLOverDataGenL->GetXaxis()->SetTitle("|#eta|");
   DataGenLOverDataGenL->GetXaxis()->SetNdivisions(511);
   DataGenLOverDataGenL->GetXaxis()->SetLabelFont(42);
   DataGenLOverDataGenL->GetXaxis()->SetLabelOffset(0.007);
   DataGenLOverDataGenL->GetXaxis()->SetLabelSize(0.05);
   DataGenLOverDataGenL->GetXaxis()->SetTitleSize(0.05);
   DataGenLOverDataGenL->GetXaxis()->SetTitleFont(42);
   DataGenLOverDataGenL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataGenLOverDataGenL->GetYaxis()->SetLabelFont(42);
   DataGenLOverDataGenL->GetYaxis()->SetLabelOffset(0.007);
   DataGenLOverDataGenL->GetYaxis()->SetLabelSize(0.05);
   DataGenLOverDataGenL->GetYaxis()->SetTitleSize(0.05);
   DataGenLOverDataGenL->GetYaxis()->SetTitleFont(42);
   DataGenLOverDataGenL->GetZaxis()->SetLabelFont(42);
   DataGenLOverDataGenL->GetZaxis()->SetLabelOffset(0.007);
   DataGenLOverDataGenL->GetZaxis()->SetLabelSize(0.05);
   DataGenLOverDataGenL->GetZaxis()->SetTitleSize(0.05);
   DataGenLOverDataGenL->GetZaxis()->SetTitleFont(42);
   DataGenLOverDataGenL->Draw("same hist");
   Double_t xAxis4[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataGenLOverherwigppGenL = new TH1F("DataGenLOverherwigppGenL","DataGenLOverherwigppGenL",7, xAxis4);
   DataGenLOverherwigppGenL->SetBinContent(1,0.8158086);
   DataGenLOverherwigppGenL->SetBinContent(2,0.7291672);
   DataGenLOverherwigppGenL->SetBinContent(3,0.7269458);
   DataGenLOverherwigppGenL->SetBinContent(4,0.7420297);
   DataGenLOverherwigppGenL->SetBinContent(5,0.6245304);
   DataGenLOverherwigppGenL->SetBinContent(6,0.8670623);
   DataGenLOverherwigppGenL->SetBinContent(7,1.222513);
   DataGenLOverherwigppGenL->SetBinError(1,0.06120419);
   DataGenLOverherwigppGenL->SetBinError(2,0.04738683);
   DataGenLOverherwigppGenL->SetBinError(3,0.04698659);
   DataGenLOverherwigppGenL->SetBinError(4,0.05193021);
   DataGenLOverherwigppGenL->SetBinError(5,0.03858406);
   DataGenLOverherwigppGenL->SetBinError(6,0.07564475);
   DataGenLOverherwigppGenL->SetBinError(7,0.03369615);
   DataGenLOverherwigppGenL->SetEntries(7);
   DataGenLOverherwigppGenL->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   DataGenLOverherwigppGenL->SetLineColor(ci);
   DataGenLOverherwigppGenL->SetLineStyle(4);
   DataGenLOverherwigppGenL->SetLineWidth(5);

   ci = TColor::GetColor("#0000ff");
   DataGenLOverherwigppGenL->SetMarkerColor(ci);
   DataGenLOverherwigppGenL->SetMarkerStyle(20);
   DataGenLOverherwigppGenL->GetXaxis()->SetTitle("|#eta|");
   DataGenLOverherwigppGenL->GetXaxis()->SetLabelFont(42);
   DataGenLOverherwigppGenL->GetXaxis()->SetLabelOffset(0.007);
   DataGenLOverherwigppGenL->GetXaxis()->SetLabelSize(0.05);
   DataGenLOverherwigppGenL->GetXaxis()->SetTitleSize(0.05);
   DataGenLOverherwigppGenL->GetXaxis()->SetTitleFont(42);
   DataGenLOverherwigppGenL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataGenLOverherwigppGenL->GetYaxis()->SetLabelFont(42);
   DataGenLOverherwigppGenL->GetYaxis()->SetLabelOffset(0.007);
   DataGenLOverherwigppGenL->GetYaxis()->SetLabelSize(0.05);
   DataGenLOverherwigppGenL->GetYaxis()->SetTitleSize(0.05);
   DataGenLOverherwigppGenL->GetYaxis()->SetTitleFont(42);
   DataGenLOverherwigppGenL->GetZaxis()->SetLabelFont(42);
   DataGenLOverherwigppGenL->GetZaxis()->SetLabelOffset(0.007);
   DataGenLOverherwigppGenL->GetZaxis()->SetLabelSize(0.05);
   DataGenLOverherwigppGenL->GetZaxis()->SetTitleSize(0.05);
   DataGenLOverherwigppGenL->GetZaxis()->SetTitleFont(42);
   DataGenLOverherwigppGenL->Draw("same hist");
   Double_t xAxis5[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataGenLOvereposGenL = new TH1F("DataGenLOvereposGenL","DataGenLOvereposGenL",7, xAxis5);
   DataGenLOvereposGenL->SetBinContent(1,0.8018597);
   DataGenLOvereposGenL->SetBinContent(2,0.6902714);
   DataGenLOvereposGenL->SetBinContent(3,0.6650487);
   DataGenLOvereposGenL->SetBinContent(4,0.6792977);
   DataGenLOvereposGenL->SetBinContent(5,0.5402871);
   DataGenLOvereposGenL->SetBinContent(6,0.7433435);
   DataGenLOvereposGenL->SetBinContent(7,1.002066);
   DataGenLOvereposGenL->SetBinError(1,0.05544703);
   DataGenLOvereposGenL->SetBinError(2,0.03768172);
   DataGenLOvereposGenL->SetBinError(3,0.03363212);
   DataGenLOvereposGenL->SetBinError(4,0.03813209);
   DataGenLOvereposGenL->SetBinError(5,0.01508123);
   DataGenLOvereposGenL->SetBinError(6,0.0503729);
   DataGenLOvereposGenL->SetBinError(7,0.01648688);
   DataGenLOvereposGenL->SetEntries(7);
   DataGenLOvereposGenL->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   DataGenLOvereposGenL->SetLineColor(ci);
   DataGenLOvereposGenL->SetLineStyle(5);
   DataGenLOvereposGenL->SetLineWidth(5);

   ci = TColor::GetColor("#ff0000");
   DataGenLOvereposGenL->SetMarkerColor(ci);
   DataGenLOvereposGenL->SetMarkerStyle(20);
   DataGenLOvereposGenL->GetXaxis()->SetTitle("|#eta|");
   DataGenLOvereposGenL->GetXaxis()->SetLabelFont(42);
   DataGenLOvereposGenL->GetXaxis()->SetLabelOffset(0.007);
   DataGenLOvereposGenL->GetXaxis()->SetLabelSize(0.05);
   DataGenLOvereposGenL->GetXaxis()->SetTitleSize(0.05);
   DataGenLOvereposGenL->GetXaxis()->SetTitleFont(42);
   DataGenLOvereposGenL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataGenLOvereposGenL->GetYaxis()->SetLabelFont(42);
   DataGenLOvereposGenL->GetYaxis()->SetLabelOffset(0.007);
   DataGenLOvereposGenL->GetYaxis()->SetLabelSize(0.05);
   DataGenLOvereposGenL->GetYaxis()->SetTitleSize(0.05);
   DataGenLOvereposGenL->GetYaxis()->SetTitleFont(42);
   DataGenLOvereposGenL->GetZaxis()->SetLabelFont(42);
   DataGenLOvereposGenL->GetZaxis()->SetLabelOffset(0.007);
   DataGenLOvereposGenL->GetZaxis()->SetLabelSize(0.05);
   DataGenLOvereposGenL->GetZaxis()->SetTitleSize(0.05);
   DataGenLOvereposGenL->GetZaxis()->SetTitleFont(42);
   DataGenLOvereposGenL->Draw("same hist");
      tex = new TLatex(0.75,0.15,"B = 0 T");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.15,"SD-Enhanced");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.3157895,0.6730435,0.5162907,0.9043478,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("DataGenLOverDataGenL","Pythia8 Monash","L");

   ci = TColor::GetColor("#006633");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("DataGenLOverherwigppGenL","EPOS-LHC","L");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(4);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("DataGenLOvereposGenL","QGSJET II","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(5);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("TotalUnc_Ratio","Total Exp. Unc.","F");

   ci = TColor::GetColor("#999999");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   TLine *line = new TLine(3.139,1,6.6,1);
   line->Draw();
   DataGenLOverMCGenL->Modified();
   DataGenLOverMCGenL->cd();
   DataGenLOverMCGenL->SetSelected(DataGenLOverMCGenL);
}
