{
//=========Macro generated from canvas: EnergyFlow_0T_MC_Det_GenLevel_Comp/EnergyFlow_0T_MC_Det_GenLevel_Comp
//=========  (Wed Aug 17 12:54:56 2016) by ROOT version5.34/30
   TCanvas *EnergyFlow_0T_MC_Det_GenLevel_Comp = new TCanvas("EnergyFlow_0T_MC_Det_GenLevel_Comp", "EnergyFlow_0T_MC_Det_GenLevel_Comp",50,72,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->Range(2.659429,-1.2,6.76419,8.8);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetFillColor(0);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetBorderMode(0);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetBorderSize(2);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetLogy();
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetTickx(1);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetTicky(1);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetLeftMargin(0.12);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetRightMargin(0.04);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetTopMargin(0.08);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetBottomMargin(0.12);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetFrameFillStyle(0);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetFrameBorderMode(0);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetFrameFillStyle(0);
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetFrameBorderMode(0);
   Double_t xAxis7[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Genpythia8Monash_Gen = new TH1F("EnergyFlow_Genpythia8Monash_Gen","EnergyFlow_Genpythia8Monash_Gen",7, xAxis7);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(1,26.01307);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(2,37.78325);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(3,54.00093);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(4,77.33501);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(5,109.4713);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(6,151.4862);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(7,181.4059);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(1,0.1226412);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(2,0.1736991);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(3,0.2415139);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(4,0.3393855);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(5,0.4709966);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(6,0.6551044);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(7,0.6175239);
   EnergyFlow_Genpythia8Monash_Gen->SetMinimum(1);
   EnergyFlow_Genpythia8Monash_Gen->SetMaximum(1e+08);
   EnergyFlow_Genpythia8Monash_Gen->SetEntries(7);
   EnergyFlow_Genpythia8Monash_Gen->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#006633");
   EnergyFlow_Genpythia8Monash_Gen->SetLineColor(ci);
   EnergyFlow_Genpythia8Monash_Gen->SetLineWidth(5);

   ci = TColor::GetColor("#006633");
   EnergyFlow_Genpythia8Monash_Gen->SetMarkerColor(ci);
   EnergyFlow_Genpythia8Monash_Gen->SetMarkerStyle(20);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetNdivisions(511);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen->Draw("AXIS");
   TLatex *   tex = new TLatex(0.96,0.936,"0.06 nb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.892,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.82,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis8[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Genpythia8Monash_Gen__2 = new TH1F("EnergyFlow_Genpythia8Monash_Gen__2","EnergyFlow_Genpythia8Monash_Gen",7, xAxis8);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinContent(1,26.01307);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinContent(2,37.78325);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinContent(3,54.00093);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinContent(4,77.33501);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinContent(5,109.4713);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinContent(6,151.4862);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinContent(7,181.4059);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinError(1,0.1226412);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinError(2,0.1736991);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinError(3,0.2415139);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinError(4,0.3393855);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinError(5,0.4709966);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinError(6,0.6551044);
   EnergyFlow_Genpythia8Monash_Gen__2->SetBinError(7,0.6175239);
   EnergyFlow_Genpythia8Monash_Gen__2->SetMinimum(1);
   EnergyFlow_Genpythia8Monash_Gen__2->SetMaximum(1e+09);
   EnergyFlow_Genpythia8Monash_Gen__2->SetEntries(7);
   EnergyFlow_Genpythia8Monash_Gen__2->SetDirectory(0);
   EnergyFlow_Genpythia8Monash_Gen__2->SetStats(0);

   ci = TColor::GetColor("#006633");
   EnergyFlow_Genpythia8Monash_Gen__2->SetLineColor(ci);
   EnergyFlow_Genpythia8Monash_Gen__2->SetLineWidth(5);

   ci = TColor::GetColor("#006633");
   EnergyFlow_Genpythia8Monash_Gen__2->SetMarkerColor(ci);
   EnergyFlow_Genpythia8Monash_Gen__2->SetMarkerStyle(20);
   EnergyFlow_Genpythia8Monash_Gen__2->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Genpythia8Monash_Gen__2->GetXaxis()->SetNdivisions(511);
   EnergyFlow_Genpythia8Monash_Gen__2->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen__2->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen__2->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen__2->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen__2->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_Genpythia8Monash_Gen__2->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen__2->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Genpythia8Monash_Gen__2->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen__2->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen__2->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen__2->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen__2->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen__2->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen__2->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen__2->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen__2->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen__2->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen__2->Draw("sameaxis");
   Double_t xAxis9[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_pythia8_Monash_CaloTower = new TH1F("EnergyFlow_pythia8_Monash_CaloTower","EnergyFlow_pythia8_Monash_CaloTower",7, xAxis9);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(1,0.3167418);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(2,0.3356895);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(3,0.3285875);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(4,0.3231191);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(5,0.2495184);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(6,0.3241591);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(7,130.0292);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(1,0.00538441);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(2,0.005624147);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(3,0.005604029);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(4,0.005676237);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(5,0.004910631);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(6,0.006005433);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(7,0.5354556);
   EnergyFlow_pythia8_Monash_CaloTower->SetEntries(7);
   EnergyFlow_pythia8_Monash_CaloTower->SetStats(0);

   ci = TColor::GetColor("#006633");
   EnergyFlow_pythia8_Monash_CaloTower->SetLineColor(ci);
   EnergyFlow_pythia8_Monash_CaloTower->SetLineStyle(2);

   ci = TColor::GetColor("#006633");
   EnergyFlow_pythia8_Monash_CaloTower->SetMarkerColor(ci);
   EnergyFlow_pythia8_Monash_CaloTower->SetMarkerStyle(26);
   EnergyFlow_pythia8_Monash_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetNdivisions(511);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->Draw("same E0");
   Double_t xAxis10[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_pythia8_TuneMBR_CaloTower = new TH1F("EnergyFlow_pythia8_TuneMBR_CaloTower","EnergyFlow_pythia8_TuneMBR_CaloTower",7, xAxis10);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(1,3.722374);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(2,4.427166);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(3,4.595312);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(4,4.939575);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(5,3.848857);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(6,5.165112);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(7,1093.766);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(1,0.05351436);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(2,0.05872208);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(3,0.06030017);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(4,0.06357548);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(5,0.05528756);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(6,0.06882722);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(7,4.215886);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetEntries(7);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetStats(0);

   ci = TColor::GetColor("#990099");
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetLineColor(ci);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetLineStyle(2);

   ci = TColor::GetColor("#990099");
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetMarkerColor(ci);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetMarkerStyle(26);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->Draw("same E0");
   Double_t xAxis11[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_epos_CaloTower = new TH1F("EnergyFlow_epos_CaloTower","EnergyFlow_epos_CaloTower",7, xAxis11);
   EnergyFlow_epos_CaloTower->SetBinContent(1,39.46015);
   EnergyFlow_epos_CaloTower->SetBinContent(2,43.79171);
   EnergyFlow_epos_CaloTower->SetBinContent(3,43.82202);
   EnergyFlow_epos_CaloTower->SetBinContent(4,40.2165);
   EnergyFlow_epos_CaloTower->SetBinContent(5,29.24455);
   EnergyFlow_epos_CaloTower->SetBinContent(6,36.07849);
   EnergyFlow_epos_CaloTower->SetBinContent(7,8870.172);
   EnergyFlow_epos_CaloTower->SetBinError(1,0.6401582);
   EnergyFlow_epos_CaloTower->SetBinError(2,0.6762136);
   EnergyFlow_epos_CaloTower->SetBinError(3,0.6845225);
   EnergyFlow_epos_CaloTower->SetBinError(4,0.6591364);
   EnergyFlow_epos_CaloTower->SetBinError(5,0.5556419);
   EnergyFlow_epos_CaloTower->SetBinError(6,0.6631785);
   EnergyFlow_epos_CaloTower->SetBinError(7,42.89786);
   EnergyFlow_epos_CaloTower->SetEntries(7);
   EnergyFlow_epos_CaloTower->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   EnergyFlow_epos_CaloTower->SetLineColor(ci);
   EnergyFlow_epos_CaloTower->SetLineStyle(2);

   ci = TColor::GetColor("#0000ff");
   EnergyFlow_epos_CaloTower->SetMarkerColor(ci);
   EnergyFlow_epos_CaloTower->SetMarkerStyle(26);
   EnergyFlow_epos_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_epos_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_epos_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_epos_CaloTower->Draw("same E0");
   Double_t xAxis12[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_qgsjetII_CaloTower = new TH1F("EnergyFlow_qgsjetII_CaloTower","EnergyFlow_qgsjetII_CaloTower",7, xAxis12);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(1,447.1926);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(2,493.9911);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(3,498.2593);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(4,503.943);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(5,377.4119);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(6,479.2223);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(7,113569.8);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(1,7.947866);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(2,8.375631);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(3,8.477962);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(4,8.655142);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(5,7.410409);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(6,8.837818);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(7,591.2261);
   EnergyFlow_qgsjetII_CaloTower->SetEntries(7);
   EnergyFlow_qgsjetII_CaloTower->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   EnergyFlow_qgsjetII_CaloTower->SetLineColor(ci);
   EnergyFlow_qgsjetII_CaloTower->SetLineStyle(2);

   ci = TColor::GetColor("#ff0000");
   EnergyFlow_qgsjetII_CaloTower->SetMarkerColor(ci);
   EnergyFlow_qgsjetII_CaloTower->SetMarkerStyle(26);
   EnergyFlow_qgsjetII_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_qgsjetII_CaloTower->Draw("same E0");
   Double_t xAxis13[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Genpythia8Monash_Gen = new TH1F("EnergyFlow_Genpythia8Monash_Gen","EnergyFlow_Genpythia8Monash_Gen",7, xAxis13);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(1,26.01307);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(2,37.78325);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(3,54.00093);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(4,77.33501);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(5,109.4713);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(6,151.4862);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(7,181.4059);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(1,0.1226412);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(2,0.1736991);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(3,0.2415139);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(4,0.3393855);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(5,0.4709966);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(6,0.6551044);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(7,0.6175239);
   EnergyFlow_Genpythia8Monash_Gen->SetMinimum(1);
   EnergyFlow_Genpythia8Monash_Gen->SetMaximum(1e+08);
   EnergyFlow_Genpythia8Monash_Gen->SetEntries(7);
   EnergyFlow_Genpythia8Monash_Gen->SetStats(0);

   ci = TColor::GetColor("#006633");
   EnergyFlow_Genpythia8Monash_Gen->SetLineColor(ci);
   EnergyFlow_Genpythia8Monash_Gen->SetLineWidth(5);

   ci = TColor::GetColor("#006633");
   EnergyFlow_Genpythia8Monash_Gen->SetMarkerColor(ci);
   EnergyFlow_Genpythia8Monash_Gen->SetMarkerStyle(20);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetNdivisions(511);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen->Draw("same hist");
   Double_t xAxis14[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Genpythia8MBR_Gen = new TH1F("EnergyFlow_Genpythia8MBR_Gen","EnergyFlow_Genpythia8MBR_Gen",7, xAxis14);
   EnergyFlow_Genpythia8MBR_Gen->SetBinContent(1,192.3085);
   EnergyFlow_Genpythia8MBR_Gen->SetBinContent(2,274.4813);
   EnergyFlow_Genpythia8MBR_Gen->SetBinContent(3,410.6619);
   EnergyFlow_Genpythia8MBR_Gen->SetBinContent(4,585.4049);
   EnergyFlow_Genpythia8MBR_Gen->SetBinContent(5,840.7529);
   EnergyFlow_Genpythia8MBR_Gen->SetBinContent(6,1177.786);
   EnergyFlow_Genpythia8MBR_Gen->SetBinContent(7,1385.894);
   EnergyFlow_Genpythia8MBR_Gen->SetBinError(1,3.048476);
   EnergyFlow_Genpythia8MBR_Gen->SetBinError(2,4.20341);
   EnergyFlow_Genpythia8MBR_Gen->SetBinError(3,6.211908);
   EnergyFlow_Genpythia8MBR_Gen->SetBinError(4,8.689919);
   EnergyFlow_Genpythia8MBR_Gen->SetBinError(5,12.02977);
   EnergyFlow_Genpythia8MBR_Gen->SetBinError(6,16.60601);
   EnergyFlow_Genpythia8MBR_Gen->SetBinError(7,15.33023);
   EnergyFlow_Genpythia8MBR_Gen->SetEntries(7);
   EnergyFlow_Genpythia8MBR_Gen->SetStats(0);

   ci = TColor::GetColor("#990099");
   EnergyFlow_Genpythia8MBR_Gen->SetLineColor(ci);
   EnergyFlow_Genpythia8MBR_Gen->SetLineStyle(2);
   EnergyFlow_Genpythia8MBR_Gen->SetLineWidth(5);

   ci = TColor::GetColor("#990099");
   EnergyFlow_Genpythia8MBR_Gen->SetMarkerColor(ci);
   EnergyFlow_Genpythia8MBR_Gen->SetMarkerStyle(20);
   EnergyFlow_Genpythia8MBR_Gen->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Genpythia8MBR_Gen->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8MBR_Gen->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8MBR_Gen->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8MBR_Gen->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8MBR_Gen->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8MBR_Gen->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Genpythia8MBR_Gen->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8MBR_Gen->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8MBR_Gen->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8MBR_Gen->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8MBR_Gen->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8MBR_Gen->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8MBR_Gen->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8MBR_Gen->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8MBR_Gen->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8MBR_Gen->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8MBR_Gen->Draw("same hist");
   Double_t xAxis15[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Genepos_Gen = new TH1F("EnergyFlow_Genepos_Gen","EnergyFlow_Genepos_Gen",7, xAxis15);
   EnergyFlow_Genepos_Gen->SetBinContent(1,1427.255);
   EnergyFlow_Genepos_Gen->SetBinContent(2,2056.171);
   EnergyFlow_Genepos_Gen->SetBinContent(3,2952.017);
   EnergyFlow_Genepos_Gen->SetBinContent(4,4204.665);
   EnergyFlow_Genepos_Gen->SetBinContent(5,5957.721);
   EnergyFlow_Genepos_Gen->SetBinContent(6,8191.525);
   EnergyFlow_Genepos_Gen->SetBinContent(7,10171.6);
   EnergyFlow_Genepos_Gen->SetBinError(1,8.319375);
   EnergyFlow_Genepos_Gen->SetBinError(2,11.61387);
   EnergyFlow_Genepos_Gen->SetBinError(3,16.52926);
   EnergyFlow_Genepos_Gen->SetBinError(4,22.74985);
   EnergyFlow_Genepos_Gen->SetBinError(5,31.65624);
   EnergyFlow_Genepos_Gen->SetBinError(6,44.04171);
   EnergyFlow_Genepos_Gen->SetBinError(7,43.16654);
   EnergyFlow_Genepos_Gen->SetEntries(7);
   EnergyFlow_Genepos_Gen->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   EnergyFlow_Genepos_Gen->SetLineColor(ci);
   EnergyFlow_Genepos_Gen->SetLineStyle(4);
   EnergyFlow_Genepos_Gen->SetLineWidth(5);

   ci = TColor::GetColor("#0000ff");
   EnergyFlow_Genepos_Gen->SetMarkerColor(ci);
   EnergyFlow_Genepos_Gen->SetMarkerStyle(20);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Genepos_Gen->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Genepos_Gen->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Genepos_Gen->Draw("same hist");
   Double_t xAxis16[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_GenqgsjetII_Gen = new TH1F("EnergyFlow_GenqgsjetII_Gen","EnergyFlow_GenqgsjetII_Gen",7, xAxis16);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(1,14520.83);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(2,21720.33);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(3,32267.66);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(4,45929.58);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(5,68866.7);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(6,95548.87);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(7,124092.8);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(1,364.7113);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(2,510.7835);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(3,724.1944);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(4,1025.887);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(5,1484.687);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(6,2077.847);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(7,2038.063);
   EnergyFlow_GenqgsjetII_Gen->SetEntries(7);
   EnergyFlow_GenqgsjetII_Gen->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   EnergyFlow_GenqgsjetII_Gen->SetLineColor(ci);
   EnergyFlow_GenqgsjetII_Gen->SetLineStyle(5);
   EnergyFlow_GenqgsjetII_Gen->SetLineWidth(5);

   ci = TColor::GetColor("#ff0000");
   EnergyFlow_GenqgsjetII_Gen->SetMarkerColor(ci);
   EnergyFlow_GenqgsjetII_Gen->SetMarkerStyle(20);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetLabelFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetTitleFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetLabelFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetTitleFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetLabelFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetTitleFont(42);
   EnergyFlow_GenqgsjetII_Gen->Draw("same hist");
   
   TLegend *leg = new TLegend(0.35,0.62,0.57,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("EnergyFlow_pythia8_Monash_CaloTower","Pythia8 Monash","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#006633");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_pythia8_TuneMBR_CaloTower","Pythia8 MBR (#times 10)","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#990099");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_epos_CaloTower","EPOS-LHC (#times 10^{2})","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_qgsjetII_CaloTower","QGSJET II (#times 10^{3})","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#ff0000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   leg->Draw();
      tex = new TLatex(0.66,0.87,"Lines : Gen Level");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   
   leg = new TLegend(0.35,0.62,0.57,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("EnergyFlow_pythia8_Monash_CaloTower","Pythia8 Monash","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#006633");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_pythia8_TuneMBR_CaloTower","Pythia8 MBR (#times 10)","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#990099");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_epos_CaloTower","EPOS-LHC (#times 10^{2})","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_qgsjetII_CaloTower","QGSJET II (#times 10^{3})","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#ff0000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   leg->Draw();
      tex = new TLatex(0.66,0.82,"Points: CaloTower");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.75,0.15,"B = 0 T");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   EnergyFlow_0T_MC_Det_GenLevel_Comp->Modified();
   EnergyFlow_0T_MC_Det_GenLevel_Comp->cd();
   EnergyFlow_0T_MC_Det_GenLevel_Comp->SetSelected(EnergyFlow_0T_MC_Det_GenLevel_Comp);
}
