{
//=========Macro generated from canvas: EnergyFlow_Data_MC_CaloTower/EnergyFlow_Data_MC_CaloTower
//=========  (Wed Aug 17 12:56:51 2016) by ROOT version5.34/30
   TCanvas *EnergyFlow_Data_MC_CaloTower = new TCanvas("EnergyFlow_Data_MC_CaloTower", "EnergyFlow_Data_MC_CaloTower",50,72,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   EnergyFlow_Data_MC_CaloTower->Range(2.659429,-1.729133,6.76419,2.643703);
   EnergyFlow_Data_MC_CaloTower->SetFillColor(0);
   EnergyFlow_Data_MC_CaloTower->SetBorderMode(0);
   EnergyFlow_Data_MC_CaloTower->SetBorderSize(2);
   EnergyFlow_Data_MC_CaloTower->SetLogy();
   EnergyFlow_Data_MC_CaloTower->SetTickx(1);
   EnergyFlow_Data_MC_CaloTower->SetTicky(1);
   EnergyFlow_Data_MC_CaloTower->SetLeftMargin(0.12);
   EnergyFlow_Data_MC_CaloTower->SetRightMargin(0.04);
   EnergyFlow_Data_MC_CaloTower->SetTopMargin(0.08);
   EnergyFlow_Data_MC_CaloTower->SetBottomMargin(0.12);
   EnergyFlow_Data_MC_CaloTower->SetFrameFillStyle(0);
   EnergyFlow_Data_MC_CaloTower->SetFrameBorderMode(0);
   EnergyFlow_Data_MC_CaloTower->SetFrameFillStyle(0);
   EnergyFlow_Data_MC_CaloTower->SetFrameBorderMode(0);
   Double_t xAxis7[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Data_CaloTower = new TH1F("EnergyFlow_Data_CaloTower","EnergyFlow_Data_CaloTower",7, xAxis7);
   EnergyFlow_Data_CaloTower->SetBinContent(1,0.2300774);
   EnergyFlow_Data_CaloTower->SetBinContent(2,0.2259026);
   EnergyFlow_Data_CaloTower->SetBinContent(3,0.2224754);
   EnergyFlow_Data_CaloTower->SetBinContent(4,0.2254556);
   EnergyFlow_Data_CaloTower->SetBinContent(5,0.1426454);
   EnergyFlow_Data_CaloTower->SetBinContent(6,0.2532609);
   EnergyFlow_Data_CaloTower->SetBinContent(7,101.4768);
   EnergyFlow_Data_CaloTower->SetBinError(1,0.02178445);
   EnergyFlow_Data_CaloTower->SetBinError(2,0.0217668);
   EnergyFlow_Data_CaloTower->SetBinError(3,0.02142404);
   EnergyFlow_Data_CaloTower->SetBinError(4,0.02274597);
   EnergyFlow_Data_CaloTower->SetBinError(5,0.01772392);
   EnergyFlow_Data_CaloTower->SetBinError(6,0.02583657);
   EnergyFlow_Data_CaloTower->SetBinError(7,2.354201);
   EnergyFlow_Data_CaloTower->SetEntries(7);
   EnergyFlow_Data_CaloTower->SetStats(0);
   EnergyFlow_Data_CaloTower->SetLineWidth(2);
   EnergyFlow_Data_CaloTower->SetMarkerStyle(20);
   EnergyFlow_Data_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Data_CaloTower->GetXaxis()->SetNdivisions(511);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->Draw("AXIS");
   TLatex *   tex = new TLatex(0.96,0.936,"0.06 nb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.892,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.82,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis8[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Data_CaloTower__2 = new TH1F("EnergyFlow_Data_CaloTower__2","EnergyFlow_Data_CaloTower",7, xAxis8);
   EnergyFlow_Data_CaloTower__2->SetBinContent(1,0.2300774);
   EnergyFlow_Data_CaloTower__2->SetBinContent(2,0.2259026);
   EnergyFlow_Data_CaloTower__2->SetBinContent(3,0.2224754);
   EnergyFlow_Data_CaloTower__2->SetBinContent(4,0.2254556);
   EnergyFlow_Data_CaloTower__2->SetBinContent(5,0.1426454);
   EnergyFlow_Data_CaloTower__2->SetBinContent(6,0.2532609);
   EnergyFlow_Data_CaloTower__2->SetBinContent(7,101.4768);
   EnergyFlow_Data_CaloTower__2->SetBinError(1,0.02178445);
   EnergyFlow_Data_CaloTower__2->SetBinError(2,0.0217668);
   EnergyFlow_Data_CaloTower__2->SetBinError(3,0.02142404);
   EnergyFlow_Data_CaloTower__2->SetBinError(4,0.02274597);
   EnergyFlow_Data_CaloTower__2->SetBinError(5,0.01772392);
   EnergyFlow_Data_CaloTower__2->SetBinError(6,0.02583657);
   EnergyFlow_Data_CaloTower__2->SetBinError(7,2.354201);
   EnergyFlow_Data_CaloTower__2->SetEntries(7);
   EnergyFlow_Data_CaloTower__2->SetDirectory(0);
   EnergyFlow_Data_CaloTower__2->SetStats(0);
   EnergyFlow_Data_CaloTower__2->SetLineWidth(2);
   EnergyFlow_Data_CaloTower__2->SetMarkerStyle(20);
   EnergyFlow_Data_CaloTower__2->SetMarkerSize(1.5);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetNdivisions(511);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower__2->Draw("sameaxis");
   Double_t xAxis9[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Data_CaloTower = new TH1F("EnergyFlow_Data_CaloTower","EnergyFlow_Data_CaloTower",7, xAxis9);
   EnergyFlow_Data_CaloTower->SetBinContent(1,0.2300774);
   EnergyFlow_Data_CaloTower->SetBinContent(2,0.2259026);
   EnergyFlow_Data_CaloTower->SetBinContent(3,0.2224754);
   EnergyFlow_Data_CaloTower->SetBinContent(4,0.2254556);
   EnergyFlow_Data_CaloTower->SetBinContent(5,0.1426454);
   EnergyFlow_Data_CaloTower->SetBinContent(6,0.2532609);
   EnergyFlow_Data_CaloTower->SetBinContent(7,101.4768);
   EnergyFlow_Data_CaloTower->SetBinError(1,0.02178445);
   EnergyFlow_Data_CaloTower->SetBinError(2,0.0217668);
   EnergyFlow_Data_CaloTower->SetBinError(3,0.02142404);
   EnergyFlow_Data_CaloTower->SetBinError(4,0.02274597);
   EnergyFlow_Data_CaloTower->SetBinError(5,0.01772392);
   EnergyFlow_Data_CaloTower->SetBinError(6,0.02583657);
   EnergyFlow_Data_CaloTower->SetBinError(7,2.354201);
   EnergyFlow_Data_CaloTower->SetEntries(7);
   EnergyFlow_Data_CaloTower->SetStats(0);
   EnergyFlow_Data_CaloTower->SetLineWidth(2);
   EnergyFlow_Data_CaloTower->SetMarkerStyle(20);
   EnergyFlow_Data_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Data_CaloTower->GetXaxis()->SetNdivisions(511);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->Draw("same");
   Double_t xAxis10[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_pythia8_Monash_CaloTower = new TH1F("EnergyFlow_pythia8_Monash_CaloTower","EnergyFlow_pythia8_Monash_CaloTower",7, xAxis10);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(1,0.3167418);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(2,0.3356895);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(3,0.3285875);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(4,0.3231191);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(5,0.2495184);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(6,0.3241591);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinContent(7,130.0292);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(1,0.00538441);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(2,0.005624147);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(3,0.005604029);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(4,0.005676237);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(5,0.004910631);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(6,0.006005433);
   EnergyFlow_pythia8_Monash_CaloTower->SetBinError(7,0.5354556);
   EnergyFlow_pythia8_Monash_CaloTower->SetMinimum(1);
   EnergyFlow_pythia8_Monash_CaloTower->SetMaximum(1e+09);
   EnergyFlow_pythia8_Monash_CaloTower->SetEntries(7);
   EnergyFlow_pythia8_Monash_CaloTower->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#006633");
   EnergyFlow_pythia8_Monash_CaloTower->SetLineColor(ci);
   EnergyFlow_pythia8_Monash_CaloTower->SetLineStyle(2);

   ci = TColor::GetColor("#006633");
   EnergyFlow_pythia8_Monash_CaloTower->SetMarkerColor(ci);
   EnergyFlow_pythia8_Monash_CaloTower->SetMarkerStyle(26);
   EnergyFlow_pythia8_Monash_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetNdivisions(511);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_pythia8_Monash_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_Monash_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_Monash_CaloTower->Draw("same");
   Double_t xAxis11[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_pythia8_TuneMBR_CaloTower = new TH1F("EnergyFlow_pythia8_TuneMBR_CaloTower","EnergyFlow_pythia8_TuneMBR_CaloTower",7, xAxis11);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(1,0.3722374);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(2,0.4427166);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(3,0.4595312);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(4,0.4939575);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(5,0.3848857);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(6,0.5165112);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinContent(7,109.3766);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(1,0.005351436);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(2,0.005872208);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(3,0.006030017);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(4,0.006357548);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(5,0.005528756);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(6,0.006882722);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetBinError(7,0.4215886);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetMinimum(1);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetMaximum(1e+09);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetEntries(7);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetStats(0);

   ci = TColor::GetColor("#990099");
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetLineColor(ci);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetLineStyle(2);

   ci = TColor::GetColor("#990099");
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetMarkerColor(ci);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetMarkerStyle(26);
   EnergyFlow_pythia8_TuneMBR_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_pythia8_TuneMBR_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_pythia8_TuneMBR_CaloTower->Draw("same");
   Double_t xAxis12[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_epos_CaloTower = new TH1F("EnergyFlow_epos_CaloTower","EnergyFlow_epos_CaloTower",7, xAxis12);
   EnergyFlow_epos_CaloTower->SetBinContent(1,0.3946015);
   EnergyFlow_epos_CaloTower->SetBinContent(2,0.4379171);
   EnergyFlow_epos_CaloTower->SetBinContent(3,0.4382202);
   EnergyFlow_epos_CaloTower->SetBinContent(4,0.402165);
   EnergyFlow_epos_CaloTower->SetBinContent(5,0.2924455);
   EnergyFlow_epos_CaloTower->SetBinContent(6,0.3607849);
   EnergyFlow_epos_CaloTower->SetBinContent(7,88.70172);
   EnergyFlow_epos_CaloTower->SetBinError(1,0.006401582);
   EnergyFlow_epos_CaloTower->SetBinError(2,0.006762136);
   EnergyFlow_epos_CaloTower->SetBinError(3,0.006845225);
   EnergyFlow_epos_CaloTower->SetBinError(4,0.006591364);
   EnergyFlow_epos_CaloTower->SetBinError(5,0.005556419);
   EnergyFlow_epos_CaloTower->SetBinError(6,0.006631785);
   EnergyFlow_epos_CaloTower->SetBinError(7,0.4289786);
   EnergyFlow_epos_CaloTower->SetMinimum(1);
   EnergyFlow_epos_CaloTower->SetMaximum(1e+09);
   EnergyFlow_epos_CaloTower->SetEntries(7);
   EnergyFlow_epos_CaloTower->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   EnergyFlow_epos_CaloTower->SetLineColor(ci);
   EnergyFlow_epos_CaloTower->SetLineStyle(2);

   ci = TColor::GetColor("#0000ff");
   EnergyFlow_epos_CaloTower->SetMarkerColor(ci);
   EnergyFlow_epos_CaloTower->SetMarkerStyle(26);
   EnergyFlow_epos_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_epos_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_epos_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_epos_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_epos_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_epos_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_epos_CaloTower->Draw("same");
   Double_t xAxis13[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_qgsjetII_CaloTower = new TH1F("EnergyFlow_qgsjetII_CaloTower","EnergyFlow_qgsjetII_CaloTower",7, xAxis13);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(1,0.4471926);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(2,0.493991);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(3,0.4982593);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(4,0.503943);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(5,0.3774119);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(6,0.4792223);
   EnergyFlow_qgsjetII_CaloTower->SetBinContent(7,113.5698);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(1,0.007947866);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(2,0.008375631);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(3,0.008477962);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(4,0.008655142);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(5,0.007410409);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(6,0.008837818);
   EnergyFlow_qgsjetII_CaloTower->SetBinError(7,0.5912261);
   EnergyFlow_qgsjetII_CaloTower->SetMinimum(1);
   EnergyFlow_qgsjetII_CaloTower->SetMaximum(1e+09);
   EnergyFlow_qgsjetII_CaloTower->SetEntries(7);
   EnergyFlow_qgsjetII_CaloTower->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   EnergyFlow_qgsjetII_CaloTower->SetLineColor(ci);
   EnergyFlow_qgsjetII_CaloTower->SetLineStyle(2);

   ci = TColor::GetColor("#ff0000");
   EnergyFlow_qgsjetII_CaloTower->SetMarkerColor(ci);
   EnergyFlow_qgsjetII_CaloTower->SetMarkerStyle(26);
   EnergyFlow_qgsjetII_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_qgsjetII_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_qgsjetII_CaloTower->Draw("same");
   
   TLegend *leg = new TLegend(0.3270677,0.6278261,0.5463659,0.9008696,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("EnergyFlow_Data_CaloTower","DATA","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_pythia8_Monash_CaloTower","Pythia8 Monash","PL");

   ci = TColor::GetColor("#006633");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#006633");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_pythia8_TuneMBR_CaloTower","Pythia8 MBR","PL");

   ci = TColor::GetColor("#990099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#990099");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_epos_CaloTower","EPOS-LHC","PL");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_qgsjetII_CaloTower","QGSJET II","PL");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#ff0000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   leg->Draw();
      tex = new TLatex(0.75,0.15,"B = 0 T");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.75,0.2,"CaloTower");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   EnergyFlow_Data_MC_CaloTower->Modified();
   EnergyFlow_Data_MC_CaloTower->cd();
   EnergyFlow_Data_MC_CaloTower->SetSelected(EnergyFlow_Data_MC_CaloTower);
}
