{
//=========Macro generated from canvas: MCDetLOverMCGenL/MCDetLOverMCGenL
//=========  (Wed Aug 17 12:54:31 2016) by ROOT version5.34/30
   TCanvas *MCDetLOverMCGenL = new TCanvas("MCDetLOverMCGenL", "MCDetLOverMCGenL",50,72,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   MCDetLOverMCGenL->Range(2.659429,-0.635,6.76419,5.49);
   MCDetLOverMCGenL->SetFillColor(0);
   MCDetLOverMCGenL->SetBorderMode(0);
   MCDetLOverMCGenL->SetBorderSize(2);
   MCDetLOverMCGenL->SetTickx(1);
   MCDetLOverMCGenL->SetTicky(1);
   MCDetLOverMCGenL->SetLeftMargin(0.12);
   MCDetLOverMCGenL->SetRightMargin(0.04);
   MCDetLOverMCGenL->SetTopMargin(0.08);
   MCDetLOverMCGenL->SetBottomMargin(0.12);
   MCDetLOverMCGenL->SetFrameFillStyle(0);
   MCDetLOverMCGenL->SetFrameBorderMode(0);
   MCDetLOverMCGenL->SetFrameFillStyle(0);
   MCDetLOverMCGenL->SetFrameBorderMode(0);
   Double_t xAxis1[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *pythia8_MonashDetLOverpythia8_MonashGenL = new TH1F("pythia8_MonashDetLOverpythia8_MonashGenL","pythia8_MonashDetLOverpythia8_MonashGenL",7, xAxis1);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(1,51.66287);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(2,61.99933);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(3,89.3654);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(4,118.5132);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(5,218.4423);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(6,228.0272);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(7,1.267085);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(1,8.250926);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(2,10.49778);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(3,17.98332);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(4,26.98446);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(5,65.17915);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(6,68.51578);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(7,0.0166593);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetMinimum(0.1);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetMaximum(5);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetEntries(7);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#990099");
   pythia8_MonashDetLOverpythia8_MonashGenL->SetLineColor(ci);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetLineStyle(2);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetLineWidth(5);

   ci = TColor::GetColor("#990099");
   pythia8_MonashDetLOverpythia8_MonashGenL->SetMarkerColor(ci);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetMarkerStyle(20);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetTitle("|#eta|");
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetLabelFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetLabelOffset(0.007);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetLabelSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetTitleSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetTitleOffset(0.9);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetTitleFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[had] / #frac{dE}{d|#eta|}[det]");
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetLabelFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetLabelOffset(0.007);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetLabelSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetTitleSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetTitleFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetLabelFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetLabelOffset(0.007);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetLabelSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetTitleSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetTitleFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->Draw("AXIS");
   TLatex *   tex = new TLatex(0.96,0.936,"0.06 nb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.892,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.82,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis2[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *pythia8_MonashDetLOverpythia8_MonashGenL__1 = new TH1F("pythia8_MonashDetLOverpythia8_MonashGenL__1","pythia8_MonashDetLOverpythia8_MonashGenL",7, xAxis2);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinContent(1,51.66287);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinContent(2,61.99933);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinContent(3,89.3654);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinContent(4,118.5132);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinContent(5,218.4423);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinContent(6,228.0272);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinContent(7,1.267085);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinError(1,8.250926);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinError(2,10.49778);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinError(3,17.98332);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinError(4,26.98446);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinError(5,65.17915);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinError(6,68.51578);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetBinError(7,0.0166593);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetMinimum(0.1);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetMaximum(3);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetEntries(7);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetDirectory(0);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetStats(0);

   ci = TColor::GetColor("#990099");
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetLineColor(ci);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetLineStyle(2);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetLineWidth(5);

   ci = TColor::GetColor("#990099");
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetMarkerColor(ci);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->SetMarkerStyle(20);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetXaxis()->SetTitle("|#eta|");
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetXaxis()->SetLabelFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetXaxis()->SetLabelOffset(0.007);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetXaxis()->SetLabelSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetXaxis()->SetTitleSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetXaxis()->SetTitleOffset(0.9);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetXaxis()->SetTitleFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[had] / #frac{dE}{d|#eta|}[det]");
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetYaxis()->SetLabelFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetYaxis()->SetLabelOffset(0.007);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetYaxis()->SetLabelSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetYaxis()->SetTitleSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetYaxis()->SetTitleFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetZaxis()->SetLabelFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetZaxis()->SetLabelOffset(0.007);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetZaxis()->SetLabelSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetZaxis()->SetTitleSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->GetZaxis()->SetTitleFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL__1->Draw("sameaxis");
   Double_t xAxis3[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataDetLOverDataGenL = new TH1F("DataDetLOverDataGenL","DataDetLOverDataGenL",7, xAxis3);
   DataDetLOverDataGenL->SetBinContent(1,82.12706);
   DataDetLOverDataGenL->SetBinContent(2,112.5541);
   DataDetLOverDataGenL->SetBinContent(3,164.3426);
   DataDetLOverDataGenL->SetBinContent(4,239.339);
   DataDetLOverDataGenL->SetBinContent(5,438.7303);
   DataDetLOverDataGenL->SetBinContent(6,467.3205);
   DataDetLOverDataGenL->SetBinContent(7,1.395117);
   DataDetLOverDataGenL->SetBinError(1,4.746164);
   DataDetLOverDataGenL->SetBinError(2,7.513164);
   DataDetLOverDataGenL->SetBinError(3,13.00657);
   DataDetLOverDataGenL->SetBinError(4,22.56779);
   DataDetLOverDataGenL->SetBinError(5,55.21216);
   DataDetLOverDataGenL->SetBinError(6,61.14083);
   DataDetLOverDataGenL->SetBinError(7,0.002715077);
   DataDetLOverDataGenL->SetMinimum(0.1);
   DataDetLOverDataGenL->SetMaximum(3);
   DataDetLOverDataGenL->SetEntries(7);
   DataDetLOverDataGenL->SetStats(0);

   ci = TColor::GetColor("#006633");
   DataDetLOverDataGenL->SetLineColor(ci);
   DataDetLOverDataGenL->SetLineWidth(5);

   ci = TColor::GetColor("#006633");
   DataDetLOverDataGenL->SetMarkerColor(ci);
   DataDetLOverDataGenL->SetMarkerStyle(20);
   DataDetLOverDataGenL->GetXaxis()->SetTitle("|#eta|");
   DataDetLOverDataGenL->GetXaxis()->SetNdivisions(511);
   DataDetLOverDataGenL->GetXaxis()->SetLabelFont(42);
   DataDetLOverDataGenL->GetXaxis()->SetLabelOffset(0.007);
   DataDetLOverDataGenL->GetXaxis()->SetLabelSize(0.05);
   DataDetLOverDataGenL->GetXaxis()->SetTitleSize(0.05);
   DataDetLOverDataGenL->GetXaxis()->SetTitleFont(42);
   DataDetLOverDataGenL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[had] / #frac{dE}{d|#eta|}[det]");
   DataDetLOverDataGenL->GetYaxis()->SetLabelFont(42);
   DataDetLOverDataGenL->GetYaxis()->SetLabelOffset(0.007);
   DataDetLOverDataGenL->GetYaxis()->SetLabelSize(0.05);
   DataDetLOverDataGenL->GetYaxis()->SetTitleSize(0.05);
   DataDetLOverDataGenL->GetYaxis()->SetTitleFont(42);
   DataDetLOverDataGenL->GetZaxis()->SetLabelFont(42);
   DataDetLOverDataGenL->GetZaxis()->SetLabelOffset(0.007);
   DataDetLOverDataGenL->GetZaxis()->SetLabelSize(0.05);
   DataDetLOverDataGenL->GetZaxis()->SetTitleSize(0.05);
   DataDetLOverDataGenL->GetZaxis()->SetTitleFont(42);
   DataDetLOverDataGenL->Draw("same hist");
   Double_t xAxis4[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *pythia8_MonashDetLOverpythia8_MonashGenL = new TH1F("pythia8_MonashDetLOverpythia8_MonashGenL","pythia8_MonashDetLOverpythia8_MonashGenL",7, xAxis4);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(1,51.66287);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(2,61.99933);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(3,89.3654);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(4,118.5132);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(5,218.4423);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(6,228.0272);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinContent(7,1.267085);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(1,8.250926);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(2,10.49778);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(3,17.98332);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(4,26.98446);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(5,65.17915);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(6,68.51578);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetBinError(7,0.0166593);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetMinimum(0.1);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetMaximum(5);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetEntries(7);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetStats(0);

   ci = TColor::GetColor("#990099");
   pythia8_MonashDetLOverpythia8_MonashGenL->SetLineColor(ci);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetLineStyle(2);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetLineWidth(5);

   ci = TColor::GetColor("#990099");
   pythia8_MonashDetLOverpythia8_MonashGenL->SetMarkerColor(ci);
   pythia8_MonashDetLOverpythia8_MonashGenL->SetMarkerStyle(20);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetTitle("|#eta|");
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetLabelFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetLabelOffset(0.007);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetLabelSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetTitleSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetTitleOffset(0.9);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetXaxis()->SetTitleFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[had] / #frac{dE}{d|#eta|}[det]");
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetLabelFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetLabelOffset(0.007);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetLabelSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetTitleSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetYaxis()->SetTitleFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetLabelFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetLabelOffset(0.007);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetLabelSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetTitleSize(0.05);
   pythia8_MonashDetLOverpythia8_MonashGenL->GetZaxis()->SetTitleFont(42);
   pythia8_MonashDetLOverpythia8_MonashGenL->Draw("same hist");
   Double_t xAxis5[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *herwigppDetLOverherwigppGenL = new TH1F("herwigppDetLOverherwigppGenL","herwigppDetLOverherwigppGenL",7, xAxis5);
   herwigppDetLOverherwigppGenL->SetBinContent(1,36.16954);
   herwigppDetLOverherwigppGenL->SetBinContent(2,46.95343);
   herwigppDetLOverherwigppGenL->SetBinContent(3,67.36377);
   herwigppDetLOverherwigppGenL->SetBinContent(4,104.5507);
   herwigppDetLOverherwigppGenL->SetBinContent(5,203.7207);
   herwigppDetLOverherwigppGenL->SetBinContent(6,227.0474);
   herwigppDetLOverherwigppGenL->SetBinContent(7,1.14672);
   herwigppDetLOverherwigppGenL->SetBinError(1,1.681267);
   herwigppDetLOverherwigppGenL->SetBinError(2,2.451307);
   herwigppDetLOverherwigppGenL->SetBinError(3,4.23303);
   herwigppDetLOverherwigppGenL->SetBinError(4,7.978469);
   herwigppDetLOverherwigppGenL->SetBinError(5,21.47694);
   herwigppDetLOverherwigppGenL->SetBinError(6,25.64691);
   herwigppDetLOverherwigppGenL->SetBinError(7,0.0003512099);
   herwigppDetLOverherwigppGenL->SetMinimum(0.1);
   herwigppDetLOverherwigppGenL->SetMaximum(3);
   herwigppDetLOverherwigppGenL->SetEntries(7);
   herwigppDetLOverherwigppGenL->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   herwigppDetLOverherwigppGenL->SetLineColor(ci);
   herwigppDetLOverherwigppGenL->SetLineStyle(4);
   herwigppDetLOverherwigppGenL->SetLineWidth(5);

   ci = TColor::GetColor("#0000ff");
   herwigppDetLOverherwigppGenL->SetMarkerColor(ci);
   herwigppDetLOverherwigppGenL->SetMarkerStyle(20);
   herwigppDetLOverherwigppGenL->GetXaxis()->SetTitle("|#eta|");
   herwigppDetLOverherwigppGenL->GetXaxis()->SetLabelFont(42);
   herwigppDetLOverherwigppGenL->GetXaxis()->SetLabelOffset(0.007);
   herwigppDetLOverherwigppGenL->GetXaxis()->SetLabelSize(0.05);
   herwigppDetLOverherwigppGenL->GetXaxis()->SetTitleSize(0.05);
   herwigppDetLOverherwigppGenL->GetXaxis()->SetTitleFont(42);
   herwigppDetLOverherwigppGenL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[had] / #frac{dE}{d|#eta|}[det]");
   herwigppDetLOverherwigppGenL->GetYaxis()->SetLabelFont(42);
   herwigppDetLOverherwigppGenL->GetYaxis()->SetLabelOffset(0.007);
   herwigppDetLOverherwigppGenL->GetYaxis()->SetLabelSize(0.05);
   herwigppDetLOverherwigppGenL->GetYaxis()->SetTitleSize(0.05);
   herwigppDetLOverherwigppGenL->GetYaxis()->SetTitleFont(42);
   herwigppDetLOverherwigppGenL->GetZaxis()->SetLabelFont(42);
   herwigppDetLOverherwigppGenL->GetZaxis()->SetLabelOffset(0.007);
   herwigppDetLOverherwigppGenL->GetZaxis()->SetLabelSize(0.05);
   herwigppDetLOverherwigppGenL->GetZaxis()->SetTitleSize(0.05);
   herwigppDetLOverherwigppGenL->GetZaxis()->SetTitleFont(42);
   herwigppDetLOverherwigppGenL->Draw("same hist");
   Double_t xAxis6[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *eposDetLOvereposGenL = new TH1F("eposDetLOvereposGenL","eposDetLOvereposGenL",7, xAxis6);
   eposDetLOvereposGenL->SetBinContent(1,32.4711);
   eposDetLOvereposGenL->SetBinContent(2,43.96908);
   eposDetLOvereposGenL->SetBinContent(3,64.76078);
   eposDetLOvereposGenL->SetBinContent(4,91.14043);
   eposDetLOvereposGenL->SetBinContent(5,182.4709);
   eposDetLOvereposGenL->SetBinContent(6,199.3832);
   eposDetLOvereposGenL->SetBinContent(7,1.092657);
   eposDetLOvereposGenL->SetBinError(1,6.495928);
   eposDetLOvereposGenL->SetBinError(2,9.612155);
   eposDetLOvereposGenL->SetBinError(3,16.44048);
   eposDetLOvereposGenL->SetBinError(4,27.36434);
   eposDetLOvereposGenL->SetBinError(5,74.96177);
   eposDetLOvereposGenL->SetBinError(6,86.39679);
   eposDetLOvereposGenL->SetBinError(7,0.01869124);
   eposDetLOvereposGenL->SetMinimum(0.1);
   eposDetLOvereposGenL->SetMaximum(3);
   eposDetLOvereposGenL->SetEntries(7);
   eposDetLOvereposGenL->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   eposDetLOvereposGenL->SetLineColor(ci);
   eposDetLOvereposGenL->SetLineStyle(5);
   eposDetLOvereposGenL->SetLineWidth(5);

   ci = TColor::GetColor("#ff0000");
   eposDetLOvereposGenL->SetMarkerColor(ci);
   eposDetLOvereposGenL->SetMarkerStyle(20);
   eposDetLOvereposGenL->GetXaxis()->SetTitle("|#eta|");
   eposDetLOvereposGenL->GetXaxis()->SetLabelFont(42);
   eposDetLOvereposGenL->GetXaxis()->SetLabelOffset(0.007);
   eposDetLOvereposGenL->GetXaxis()->SetLabelSize(0.05);
   eposDetLOvereposGenL->GetXaxis()->SetTitleSize(0.05);
   eposDetLOvereposGenL->GetXaxis()->SetTitleFont(42);
   eposDetLOvereposGenL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[had] / #frac{dE}{d|#eta|}[det]");
   eposDetLOvereposGenL->GetYaxis()->SetLabelFont(42);
   eposDetLOvereposGenL->GetYaxis()->SetLabelOffset(0.007);
   eposDetLOvereposGenL->GetYaxis()->SetLabelSize(0.05);
   eposDetLOvereposGenL->GetYaxis()->SetTitleSize(0.05);
   eposDetLOvereposGenL->GetYaxis()->SetTitleFont(42);
   eposDetLOvereposGenL->GetZaxis()->SetLabelFont(42);
   eposDetLOvereposGenL->GetZaxis()->SetLabelOffset(0.007);
   eposDetLOvereposGenL->GetZaxis()->SetLabelSize(0.05);
   eposDetLOvereposGenL->GetZaxis()->SetTitleSize(0.05);
   eposDetLOvereposGenL->GetZaxis()->SetTitleFont(42);
   eposDetLOvereposGenL->Draw("same hist");
   
   TLegend *leg = new TLegend(0.6444724,0.6311189,0.8643216,0.9055944,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("DataDetLOverDataDetL","Pythia8 Monash","L");

   ci = TColor::GetColor("#006633");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("DataDetLOverpythia8_MonashDetL","Pythia8 MBR","L");

   ci = TColor::GetColor("#990099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("DataDetLOverherwigppDetL","EPOS-LHC","L");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(4);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("DataDetLOvereposDetL","QGSJET II","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(5);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   TLine *line = new TLine(3.139,1,6.6,1);
   line->Draw();
      tex = new TLatex(0.75,0.15,"B = 0 T");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   MCDetLOverMCGenL->Modified();
   MCDetLOverMCGenL->cd();
   MCDetLOverMCGenL->SetSelected(MCDetLOverMCGenL);
}
