{
//=========Macro generated from canvas: Unfolded_Data/Unfolded_Data
//=========  (Wed Aug 17 12:59:01 2016) by ROOT version5.34/30
   TCanvas *Unfolded_Data = new TCanvas("Unfolded_Data", "Unfolded_Data",50,72,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Unfolded_Data->Range(2.659429,0.4728169,6.76419,2.548181);
   Unfolded_Data->SetFillColor(0);
   Unfolded_Data->SetBorderMode(0);
   Unfolded_Data->SetBorderSize(2);
   Unfolded_Data->SetLogy();
   Unfolded_Data->SetTickx(1);
   Unfolded_Data->SetTicky(1);
   Unfolded_Data->SetLeftMargin(0.12);
   Unfolded_Data->SetRightMargin(0.04);
   Unfolded_Data->SetTopMargin(0.08);
   Unfolded_Data->SetBottomMargin(0.12);
   Unfolded_Data->SetFrameFillStyle(0);
   Unfolded_Data->SetFrameBorderMode(0);
   Unfolded_Data->SetFrameFillStyle(0);
   Unfolded_Data->SetFrameBorderMode(0);
   Double_t xAxis6[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Data_CaloTower = new TH1F("EnergyFlow_Data_CaloTower","EnergyFlow_Data_CaloTower",7, xAxis6);
   EnergyFlow_Data_CaloTower->SetBinContent(1,11.64367);
   EnergyFlow_Data_CaloTower->SetBinContent(2,14.99293);
   EnergyFlow_Data_CaloTower->SetBinContent(3,21.45956);
   EnergyFlow_Data_CaloTower->SetBinContent(4,31.19986);
   EnergyFlow_Data_CaloTower->SetBinContent(5,37.20778);
   EnergyFlow_Data_CaloTower->SetBinContent(6,71.02563);
   EnergyFlow_Data_CaloTower->SetBinContent(7,124.3491);
   EnergyFlow_Data_CaloTower->SetBinError(1,1.10246);
   EnergyFlow_Data_CaloTower->SetBinError(2,1.444641);
   EnergyFlow_Data_CaloTower->SetBinError(3,2.066523);
   EnergyFlow_Data_CaloTower->SetBinError(4,3.147721);
   EnergyFlow_Data_CaloTower->SetBinError(5,4.623126);
   EnergyFlow_Data_CaloTower->SetBinError(6,7.245724);
   EnergyFlow_Data_CaloTower->SetBinError(7,2.884826);
   EnergyFlow_Data_CaloTower->SetEntries(14);
   EnergyFlow_Data_CaloTower->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#999999");
   EnergyFlow_Data_CaloTower->SetFillColor(ci);
   EnergyFlow_Data_CaloTower->SetLineWidth(2);
   EnergyFlow_Data_CaloTower->SetMarkerStyle(20);
   EnergyFlow_Data_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Data_CaloTower->GetXaxis()->SetNdivisions(511);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->Draw("AXIS");
   TLatex *   tex = new TLatex(0.96,0.936,"0.06 nb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.892,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.82,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis7[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Data_CaloTower__2 = new TH1F("EnergyFlow_Data_CaloTower__2","EnergyFlow_Data_CaloTower",7, xAxis7);
   EnergyFlow_Data_CaloTower__2->SetBinContent(1,11.64367);
   EnergyFlow_Data_CaloTower__2->SetBinContent(2,14.99293);
   EnergyFlow_Data_CaloTower__2->SetBinContent(3,21.45956);
   EnergyFlow_Data_CaloTower__2->SetBinContent(4,31.19986);
   EnergyFlow_Data_CaloTower__2->SetBinContent(5,37.20778);
   EnergyFlow_Data_CaloTower__2->SetBinContent(6,71.02563);
   EnergyFlow_Data_CaloTower__2->SetBinContent(7,124.3491);
   EnergyFlow_Data_CaloTower__2->SetBinError(1,1.10246);
   EnergyFlow_Data_CaloTower__2->SetBinError(2,1.444641);
   EnergyFlow_Data_CaloTower__2->SetBinError(3,2.066523);
   EnergyFlow_Data_CaloTower__2->SetBinError(4,3.147721);
   EnergyFlow_Data_CaloTower__2->SetBinError(5,4.623126);
   EnergyFlow_Data_CaloTower__2->SetBinError(6,7.245724);
   EnergyFlow_Data_CaloTower__2->SetBinError(7,2.884826);
   EnergyFlow_Data_CaloTower__2->SetEntries(14);
   EnergyFlow_Data_CaloTower__2->SetDirectory(0);
   EnergyFlow_Data_CaloTower__2->SetStats(0);

   ci = TColor::GetColor("#999999");
   EnergyFlow_Data_CaloTower__2->SetFillColor(ci);
   EnergyFlow_Data_CaloTower__2->SetLineWidth(2);
   EnergyFlow_Data_CaloTower__2->SetMarkerStyle(20);
   EnergyFlow_Data_CaloTower__2->SetMarkerSize(1.5);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetNdivisions(511);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_Data_CaloTower__2->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower__2->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower__2->Draw("sameaxis");
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(7);
   grae->SetName("TotalUnc");
   grae->SetTitle("Graph");

   ci = TColor::GetColor("#999999");
   grae->SetFillColor(ci);
   grae->SetMarkerStyle(20);
   grae->SetPoint(0,3.3275,11.64367);
   grae->SetPointError(0,0.1755,0.1755,367.0044,367.0044);
   grae->SetPoint(1,3.678,14.99293);
   grae->SetPointError(1,0.175,0.175,692.4521,692.4521);
   grae->SetPoint(2,4.0285,21.45956);
   grae->SetPointError(2,0.1755,0.1755,1456.773,1456.773);
   grae->SetPoint(3,4.378,31.19986);
   grae->SetPointError(3,0.174,0.174,3149.721,3149.721);
   grae->SetPoint(4,4.7275,37.20778);
   grae->SetPointError(4,0.1754999,0.1754999,6618.866,6618.866);
   grae->SetPoint(5,5.054,71.02563);
   grae->SetPointError(5,0.151,0.151,13272.99,13272.99);
   grae->SetPoint(6,5.9025,124.3491);
   grae->SetPointError(6,0.6975,0.6975,31.50282,31.50282);
   
   TH1F *Graph_TotalUnc2 = new TH1F("Graph_TotalUnc2","Graph",100,2.8072,6.9448);
   Graph_TotalUnc2->SetMinimum(3.493102);
   Graph_TotalUnc2->SetMaximum(14678.03);
   Graph_TotalUnc2->SetDirectory(0);
   Graph_TotalUnc2->SetStats(0);
   Graph_TotalUnc2->SetLineStyle(0);
   Graph_TotalUnc2->SetMarkerStyle(20);
   Graph_TotalUnc2->GetXaxis()->SetLabelFont(42);
   Graph_TotalUnc2->GetXaxis()->SetLabelOffset(0.007);
   Graph_TotalUnc2->GetXaxis()->SetLabelSize(0.05);
   Graph_TotalUnc2->GetXaxis()->SetTitleSize(0.05);
   Graph_TotalUnc2->GetXaxis()->SetTitleFont(42);
   Graph_TotalUnc2->GetYaxis()->SetLabelFont(42);
   Graph_TotalUnc2->GetYaxis()->SetLabelOffset(0.007);
   Graph_TotalUnc2->GetYaxis()->SetLabelSize(0.05);
   Graph_TotalUnc2->GetYaxis()->SetTitleSize(0.05);
   Graph_TotalUnc2->GetYaxis()->SetTitleFont(42);
   Graph_TotalUnc2->GetZaxis()->SetLabelFont(42);
   Graph_TotalUnc2->GetZaxis()->SetLabelOffset(0.007);
   Graph_TotalUnc2->GetZaxis()->SetLabelSize(0.05);
   Graph_TotalUnc2->GetZaxis()->SetTitleSize(0.05);
   Graph_TotalUnc2->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_TotalUnc2);
   
   grae->Draw("2");
   Double_t xAxis8[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Data_CaloTower = new TH1F("EnergyFlow_Data_CaloTower","EnergyFlow_Data_CaloTower",7, xAxis8);
   EnergyFlow_Data_CaloTower->SetBinContent(1,11.64367);
   EnergyFlow_Data_CaloTower->SetBinContent(2,14.99293);
   EnergyFlow_Data_CaloTower->SetBinContent(3,21.45956);
   EnergyFlow_Data_CaloTower->SetBinContent(4,31.19986);
   EnergyFlow_Data_CaloTower->SetBinContent(5,37.20778);
   EnergyFlow_Data_CaloTower->SetBinContent(6,71.02563);
   EnergyFlow_Data_CaloTower->SetBinContent(7,124.3491);
   EnergyFlow_Data_CaloTower->SetBinError(1,1.10246);
   EnergyFlow_Data_CaloTower->SetBinError(2,1.444641);
   EnergyFlow_Data_CaloTower->SetBinError(3,2.066523);
   EnergyFlow_Data_CaloTower->SetBinError(4,3.147721);
   EnergyFlow_Data_CaloTower->SetBinError(5,4.623126);
   EnergyFlow_Data_CaloTower->SetBinError(6,7.245724);
   EnergyFlow_Data_CaloTower->SetBinError(7,2.884826);
   EnergyFlow_Data_CaloTower->SetEntries(14);
   EnergyFlow_Data_CaloTower->SetStats(0);

   ci = TColor::GetColor("#999999");
   EnergyFlow_Data_CaloTower->SetFillColor(ci);
   EnergyFlow_Data_CaloTower->SetLineWidth(2);
   EnergyFlow_Data_CaloTower->SetMarkerStyle(20);
   EnergyFlow_Data_CaloTower->SetMarkerSize(1.5);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Data_CaloTower->GetXaxis()->SetNdivisions(511);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleOffset(0.9);
   EnergyFlow_Data_CaloTower->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Data_CaloTower->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Data_CaloTower->Draw("same");
   Double_t xAxis9[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Genpythia8Monash_Gen = new TH1F("EnergyFlow_Genpythia8Monash_Gen","EnergyFlow_Genpythia8Monash_Gen",7, xAxis9);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(1,26.01307);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(2,37.78325);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(3,54.00093);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(4,77.33501);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(5,109.4713);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(6,151.4862);
   EnergyFlow_Genpythia8Monash_Gen->SetBinContent(7,181.4059);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(1,0.1226412);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(2,0.1736991);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(3,0.2415139);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(4,0.3393855);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(5,0.4709966);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(6,0.6551044);
   EnergyFlow_Genpythia8Monash_Gen->SetBinError(7,0.6175239);
   EnergyFlow_Genpythia8Monash_Gen->SetMinimum(1);
   EnergyFlow_Genpythia8Monash_Gen->SetMaximum(1e+09);
   EnergyFlow_Genpythia8Monash_Gen->SetEntries(7);
   EnergyFlow_Genpythia8Monash_Gen->SetStats(0);

   ci = TColor::GetColor("#006633");
   EnergyFlow_Genpythia8Monash_Gen->SetLineColor(ci);
   EnergyFlow_Genpythia8Monash_Gen->SetLineWidth(5);

   ci = TColor::GetColor("#006633");
   EnergyFlow_Genpythia8Monash_Gen->SetMarkerColor(ci);
   EnergyFlow_Genpythia8Monash_Gen->SetMarkerStyle(20);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Genpythia8Monash_Gen->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Genpythia8Monash_Gen->Draw("same hist");
   Double_t xAxis10[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_Genepos_Gen = new TH1F("EnergyFlow_Genepos_Gen","EnergyFlow_Genepos_Gen",7, xAxis10);
   EnergyFlow_Genepos_Gen->SetBinContent(1,14.27255);
   EnergyFlow_Genepos_Gen->SetBinContent(2,20.56171);
   EnergyFlow_Genepos_Gen->SetBinContent(3,29.52017);
   EnergyFlow_Genepos_Gen->SetBinContent(4,42.04665);
   EnergyFlow_Genepos_Gen->SetBinContent(5,59.57721);
   EnergyFlow_Genepos_Gen->SetBinContent(6,81.91525);
   EnergyFlow_Genepos_Gen->SetBinContent(7,101.716);
   EnergyFlow_Genepos_Gen->SetBinError(1,0.08319375);
   EnergyFlow_Genepos_Gen->SetBinError(2,0.1161387);
   EnergyFlow_Genepos_Gen->SetBinError(3,0.1652926);
   EnergyFlow_Genepos_Gen->SetBinError(4,0.2274985);
   EnergyFlow_Genepos_Gen->SetBinError(5,0.3165624);
   EnergyFlow_Genepos_Gen->SetBinError(6,0.4404171);
   EnergyFlow_Genepos_Gen->SetBinError(7,0.4316654);
   EnergyFlow_Genepos_Gen->SetMinimum(1);
   EnergyFlow_Genepos_Gen->SetMaximum(1e+09);
   EnergyFlow_Genepos_Gen->SetEntries(7);
   EnergyFlow_Genepos_Gen->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   EnergyFlow_Genepos_Gen->SetLineColor(ci);
   EnergyFlow_Genepos_Gen->SetLineStyle(4);
   EnergyFlow_Genepos_Gen->SetLineWidth(5);

   ci = TColor::GetColor("#0000ff");
   EnergyFlow_Genepos_Gen->SetMarkerColor(ci);
   EnergyFlow_Genepos_Gen->SetMarkerStyle(20);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_Genepos_Gen->GetXaxis()->SetLabelFont(42);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_Genepos_Gen->GetXaxis()->SetTitleFont(42);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_Genepos_Gen->GetYaxis()->SetLabelFont(42);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_Genepos_Gen->GetYaxis()->SetTitleFont(42);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetLabelFont(42);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_Genepos_Gen->GetZaxis()->SetTitleFont(42);
   EnergyFlow_Genepos_Gen->Draw("same hist");
   Double_t xAxis11[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *EnergyFlow_GenqgsjetII_Gen = new TH1F("EnergyFlow_GenqgsjetII_Gen","EnergyFlow_GenqgsjetII_Gen",7, xAxis11);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(1,14.52083);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(2,21.72033);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(3,32.26766);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(4,45.92958);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(5,68.86669);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(6,95.54887);
   EnergyFlow_GenqgsjetII_Gen->SetBinContent(7,124.0928);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(1,0.3647113);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(2,0.5107835);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(3,0.7241944);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(4,1.025887);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(5,1.484687);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(6,2.077847);
   EnergyFlow_GenqgsjetII_Gen->SetBinError(7,2.038063);
   EnergyFlow_GenqgsjetII_Gen->SetMinimum(1);
   EnergyFlow_GenqgsjetII_Gen->SetMaximum(1e+09);
   EnergyFlow_GenqgsjetII_Gen->SetEntries(7);
   EnergyFlow_GenqgsjetII_Gen->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   EnergyFlow_GenqgsjetII_Gen->SetLineColor(ci);
   EnergyFlow_GenqgsjetII_Gen->SetLineStyle(5);
   EnergyFlow_GenqgsjetII_Gen->SetLineWidth(5);

   ci = TColor::GetColor("#ff0000");
   EnergyFlow_GenqgsjetII_Gen->SetMarkerColor(ci);
   EnergyFlow_GenqgsjetII_Gen->SetMarkerStyle(20);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetTitle("|#eta|");
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetLabelFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetLabelOffset(0.007);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetLabelSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetTitleSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetXaxis()->SetTitleFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetTitle("dE/d|#eta| (GeV)");
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetLabelFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetLabelOffset(0.007);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetLabelSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetTitleSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetYaxis()->SetTitleFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetLabelFont(42);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetLabelOffset(0.007);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetLabelSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetTitleSize(0.05);
   EnergyFlow_GenqgsjetII_Gen->GetZaxis()->SetTitleFont(42);
   EnergyFlow_GenqgsjetII_Gen->Draw("same hist");
   
   TLegend *leg = new TLegend(0.6328321,0.1826087,0.8521303,0.4747826,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("EnergyFlow_Data_CaloTower","Data","PLF");

   ci = TColor::GetColor("#999999");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_Genpythia8Monash_Gen","Pythia8 Monash","L");

   ci = TColor::GetColor("#006633");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_Genepos_Gen","EPOS-LHC","L");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(4);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyFlow_GenqgsjetII_Gen","QGSJET II","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(5);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
      tex = new TLatex(0.75,0.15,"B = 0 T");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.23,0.15,"SD-Enhanced");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   Unfolded_Data->Modified();
   Unfolded_Data->cd();
   Unfolded_Data->SetSelected(Unfolded_Data);
}
