{
//=========Macro generated from canvas: cCaloTowerEnergy_Comp_MC_EtaBin4/cCaloTowerEnergy_Comp_MC_EtaBin4
//=========  (Wed Aug 17 13:00:55 2016) by ROOT version5.34/30
   TCanvas *cCaloTowerEnergy_Comp_MC_EtaBin4 = new TCanvas("cCaloTowerEnergy_Comp_MC_EtaBin4", "cCaloTowerEnergy_Comp_MC_EtaBin4",50,72,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cCaloTowerEnergy_Comp_MC_EtaBin4->Range(-85.71429,-5.9,628.5714,1.6);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetFillColor(0);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetBorderMode(0);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetBorderSize(2);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetLogy();
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetTickx(1);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetTicky(1);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetLeftMargin(0.12);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetRightMargin(0.04);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetTopMargin(0.08);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetBottomMargin(0.12);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetFrameFillStyle(0);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetFrameBorderMode(0);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetFrameFillStyle(0);
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetFrameBorderMode(0);
   
   TH1F *EnergyDist_Data_EtaBin4 = new TH1F("EnergyDist_Data_EtaBin4","EnergyDist_Data_EtaBin4",600,0,600);
   EnergyDist_Data_EtaBin4->SetBinContent(5,0.01559124);
   EnergyDist_Data_EtaBin4->SetBinContent(9,0.0007285626);
   EnergyDist_Data_EtaBin4->SetBinContent(10,0.000291425);
   EnergyDist_Data_EtaBin4->SetBinError(5,0.001507262);
   EnergyDist_Data_EtaBin4->SetBinError(9,0.0003258231);
   EnergyDist_Data_EtaBin4->SetBinError(10,0.0002060686);
   EnergyDist_Data_EtaBin4->SetMinimum(1e-05);
   EnergyDist_Data_EtaBin4->SetMaximum(10);
   EnergyDist_Data_EtaBin4->SetEntries(114);
   EnergyDist_Data_EtaBin4->SetStats(0);
   EnergyDist_Data_EtaBin4->SetLineStyle(0);
   EnergyDist_Data_EtaBin4->SetMarkerStyle(20);
   EnergyDist_Data_EtaBin4->SetMarkerSize(0.5);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetTitle("Energy");
   EnergyDist_Data_EtaBin4->GetXaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetTitleOffset(0.9);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetTitle("1/N");
   EnergyDist_Data_EtaBin4->GetYaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin4->Draw("AXIS");
   TLatex *   tex = new TLatex(0.96,0.936,"0.06 nb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.892,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.82,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *EnergyDist_Data_EtaBin4__3 = new TH1F("EnergyDist_Data_EtaBin4__3","EnergyDist_Data_EtaBin4",600,0,600);
   EnergyDist_Data_EtaBin4__3->SetBinContent(5,0.01559124);
   EnergyDist_Data_EtaBin4__3->SetBinContent(9,0.0007285626);
   EnergyDist_Data_EtaBin4__3->SetBinContent(10,0.000291425);
   EnergyDist_Data_EtaBin4__3->SetBinError(5,0.001507262);
   EnergyDist_Data_EtaBin4__3->SetBinError(9,0.0003258231);
   EnergyDist_Data_EtaBin4__3->SetBinError(10,0.0002060686);
   EnergyDist_Data_EtaBin4__3->SetMinimum(1e-05);
   EnergyDist_Data_EtaBin4__3->SetMaximum(10);
   EnergyDist_Data_EtaBin4__3->SetEntries(114);
   EnergyDist_Data_EtaBin4__3->SetDirectory(0);
   EnergyDist_Data_EtaBin4__3->SetStats(0);
   EnergyDist_Data_EtaBin4__3->SetLineStyle(0);
   EnergyDist_Data_EtaBin4__3->SetMarkerStyle(20);
   EnergyDist_Data_EtaBin4__3->SetMarkerSize(0.5);
   EnergyDist_Data_EtaBin4__3->GetXaxis()->SetTitle("Energy");
   EnergyDist_Data_EtaBin4__3->GetXaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin4__3->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin4__3->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin4__3->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin4__3->GetXaxis()->SetTitleOffset(0.9);
   EnergyDist_Data_EtaBin4__3->GetXaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin4__3->GetYaxis()->SetTitle("1/N");
   EnergyDist_Data_EtaBin4__3->GetYaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin4__3->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin4__3->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin4__3->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin4__3->GetYaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin4__3->GetZaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin4__3->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin4__3->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin4__3->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin4__3->GetZaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin4__3->Draw("sameaxis");
   
   TH1F *EnergyDist_Data_EtaBin4 = new TH1F("EnergyDist_Data_EtaBin4","EnergyDist_Data_EtaBin4",600,0,600);
   EnergyDist_Data_EtaBin4->SetBinContent(5,0.01559124);
   EnergyDist_Data_EtaBin4->SetBinContent(9,0.0007285626);
   EnergyDist_Data_EtaBin4->SetBinContent(10,0.000291425);
   EnergyDist_Data_EtaBin4->SetBinError(5,0.001507262);
   EnergyDist_Data_EtaBin4->SetBinError(9,0.0003258231);
   EnergyDist_Data_EtaBin4->SetBinError(10,0.0002060686);
   EnergyDist_Data_EtaBin4->SetMinimum(1e-05);
   EnergyDist_Data_EtaBin4->SetMaximum(10);
   EnergyDist_Data_EtaBin4->SetEntries(114);
   EnergyDist_Data_EtaBin4->SetStats(0);
   EnergyDist_Data_EtaBin4->SetLineStyle(0);
   EnergyDist_Data_EtaBin4->SetMarkerStyle(20);
   EnergyDist_Data_EtaBin4->SetMarkerSize(0.5);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetTitle("Energy");
   EnergyDist_Data_EtaBin4->GetXaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetTitleOffset(0.9);
   EnergyDist_Data_EtaBin4->GetXaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetTitle("1/N");
   EnergyDist_Data_EtaBin4->GetYaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin4->GetYaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin4->GetZaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin4->Draw("same");
   
   TH1F *EnergyDist_pythia8_Monash_EtaBin4 = new TH1F("EnergyDist_pythia8_Monash_EtaBin4","EnergyDist_pythia8_Monash_EtaBin4",600,0,600);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinContent(5,0.02148335);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinContent(9,0.001109143);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinContent(10,0.0008192537);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinContent(13,1.890586e-05);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinContent(14,9.452928e-05);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinContent(15,1.890586e-05);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinContent(18,6.301952e-06);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinContent(19,6.301952e-06);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinError(5,0.0003679498);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinError(9,8.360484e-05);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinError(10,7.18533e-05);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinError(13,1.09153e-05);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinError(14,2.440735e-05);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinError(15,1.09153e-05);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinError(18,6.301952e-06);
   EnergyDist_pythia8_Monash_EtaBin4->SetBinError(19,6.301952e-06);
   EnergyDist_pythia8_Monash_EtaBin4->SetMinimum(1e-05);
   EnergyDist_pythia8_Monash_EtaBin4->SetMaximum(10);
   EnergyDist_pythia8_Monash_EtaBin4->SetEntries(3738);
   EnergyDist_pythia8_Monash_EtaBin4->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   EnergyDist_pythia8_Monash_EtaBin4->SetLineColor(ci);
   EnergyDist_pythia8_Monash_EtaBin4->SetLineStyle(0);

   ci = TColor::GetColor("#0000ff");
   EnergyDist_pythia8_Monash_EtaBin4->SetMarkerColor(ci);
   EnergyDist_pythia8_Monash_EtaBin4->SetMarkerStyle(24);
   EnergyDist_pythia8_Monash_EtaBin4->SetMarkerSize(0.5);
   EnergyDist_pythia8_Monash_EtaBin4->GetXaxis()->SetTitle("Energy");
   EnergyDist_pythia8_Monash_EtaBin4->GetXaxis()->SetLabelFont(42);
   EnergyDist_pythia8_Monash_EtaBin4->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_Monash_EtaBin4->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin4->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin4->GetXaxis()->SetTitleFont(42);
   EnergyDist_pythia8_Monash_EtaBin4->GetYaxis()->SetTitle("1/N");
   EnergyDist_pythia8_Monash_EtaBin4->GetYaxis()->SetLabelFont(42);
   EnergyDist_pythia8_Monash_EtaBin4->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_Monash_EtaBin4->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin4->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin4->GetYaxis()->SetTitleFont(42);
   EnergyDist_pythia8_Monash_EtaBin4->GetZaxis()->SetLabelFont(42);
   EnergyDist_pythia8_Monash_EtaBin4->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_Monash_EtaBin4->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin4->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin4->GetZaxis()->SetTitleFont(42);
   EnergyDist_pythia8_Monash_EtaBin4->Draw("same");
   
   TH1F *EnergyDist_pythia8_TuneMBR_EtaBin4 = new TH1F("EnergyDist_pythia8_TuneMBR_EtaBin4","EnergyDist_pythia8_TuneMBR_EtaBin4",600,0,600);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinContent(5,0.03087786);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinContent(9,0.001306576);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinContent(10,0.001034595);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinContent(13,4.266371e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinContent(14,0.0001066593);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinContent(15,2.133185e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinContent(18,5.332964e-06);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinContent(19,5.332964e-06);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinError(5,0.0004057961);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinError(9,8.347408e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinError(10,7.427959e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinError(13,1.50839e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinError(14,2.384974e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinError(15,1.066593e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinError(18,5.332964e-06);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetBinError(19,5.332964e-06);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetMinimum(1e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetMaximum(10);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetEntries(6263);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetLineColor(ci);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetLineStyle(0);

   ci = TColor::GetColor("#ff0000");
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetMarkerColor(ci);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetMarkerStyle(25);
   EnergyDist_pythia8_TuneMBR_EtaBin4->SetMarkerSize(0.5);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetXaxis()->SetTitle("Energy");
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetXaxis()->SetLabelFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetXaxis()->SetTitleFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetYaxis()->SetTitle("1/N");
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetYaxis()->SetLabelFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetYaxis()->SetTitleFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetZaxis()->SetLabelFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin4->GetZaxis()->SetTitleFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin4->Draw("same");
   
   TH1F *EnergyDist_epos_EtaBin4 = new TH1F("EnergyDist_epos_EtaBin4","EnergyDist_epos_EtaBin4",600,0,600);
   EnergyDist_epos_EtaBin4->SetBinContent(5,0.02914416);
   EnergyDist_epos_EtaBin4->SetBinContent(9,0.001234559);
   EnergyDist_epos_EtaBin4->SetBinContent(10,0.001077563);
   EnergyDist_epos_EtaBin4->SetBinContent(13,4.281708e-05);
   EnergyDist_epos_EtaBin4->SetBinContent(14,0.0001070427);
   EnergyDist_epos_EtaBin4->SetBinContent(15,4.281708e-05);
   EnergyDist_epos_EtaBin4->SetBinContent(18,7.13618e-06);
   EnergyDist_epos_EtaBin4->SetBinError(5,0.000456046);
   EnergyDist_epos_EtaBin4->SetBinError(9,9.386179e-05);
   EnergyDist_epos_EtaBin4->SetBinError(10,8.769084e-05);
   EnergyDist_epos_EtaBin4->SetBinError(13,1.748e-05);
   EnergyDist_epos_EtaBin4->SetBinError(14,2.763831e-05);
   EnergyDist_epos_EtaBin4->SetBinError(15,1.748e-05);
   EnergyDist_epos_EtaBin4->SetBinError(18,7.13618e-06);
   EnergyDist_epos_EtaBin4->SetMinimum(1e-05);
   EnergyDist_epos_EtaBin4->SetMaximum(10);
   EnergyDist_epos_EtaBin4->SetEntries(4436);
   EnergyDist_epos_EtaBin4->SetStats(0);

   ci = TColor::GetColor("#ff00ff");
   EnergyDist_epos_EtaBin4->SetLineColor(ci);
   EnergyDist_epos_EtaBin4->SetLineStyle(0);

   ci = TColor::GetColor("#ff00ff");
   EnergyDist_epos_EtaBin4->SetMarkerColor(ci);
   EnergyDist_epos_EtaBin4->SetMarkerStyle(27);
   EnergyDist_epos_EtaBin4->SetMarkerSize(0.5);
   EnergyDist_epos_EtaBin4->GetXaxis()->SetTitle("Energy");
   EnergyDist_epos_EtaBin4->GetXaxis()->SetLabelFont(42);
   EnergyDist_epos_EtaBin4->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_epos_EtaBin4->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_epos_EtaBin4->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_epos_EtaBin4->GetXaxis()->SetTitleFont(42);
   EnergyDist_epos_EtaBin4->GetYaxis()->SetTitle("1/N");
   EnergyDist_epos_EtaBin4->GetYaxis()->SetLabelFont(42);
   EnergyDist_epos_EtaBin4->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_epos_EtaBin4->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_epos_EtaBin4->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_epos_EtaBin4->GetYaxis()->SetTitleFont(42);
   EnergyDist_epos_EtaBin4->GetZaxis()->SetLabelFont(42);
   EnergyDist_epos_EtaBin4->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_epos_EtaBin4->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_epos_EtaBin4->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_epos_EtaBin4->GetZaxis()->SetTitleFont(42);
   EnergyDist_epos_EtaBin4->Draw("same");
   
   TH1F *EnergyDist_qgsjetII_EtaBin4 = new TH1F("EnergyDist_qgsjetII_EtaBin4","EnergyDist_qgsjetII_EtaBin4",600,0,600);
   EnergyDist_qgsjetII_EtaBin4->SetBinContent(5,0.03335906);
   EnergyDist_qgsjetII_EtaBin4->SetBinContent(9,0.001495273);
   EnergyDist_qgsjetII_EtaBin4->SetBinContent(10,0.001051515);
   EnergyDist_qgsjetII_EtaBin4->SetBinContent(13,3.858769e-05);
   EnergyDist_qgsjetII_EtaBin4->SetBinContent(14,0.0001061161);
   EnergyDist_qgsjetII_EtaBin4->SetBinContent(15,2.894077e-05);
   EnergyDist_qgsjetII_EtaBin4->SetBinContent(18,9.646923e-06);
   EnergyDist_qgsjetII_EtaBin4->SetBinContent(31,9.646923e-06);
   EnergyDist_qgsjetII_EtaBin4->SetBinError(5,0.000567285);
   EnergyDist_qgsjetII_EtaBin4->SetBinError(9,0.0001201032);
   EnergyDist_qgsjetII_EtaBin4->SetBinError(10,0.0001007168);
   EnergyDist_qgsjetII_EtaBin4->SetBinError(13,1.929385e-05);
   EnergyDist_qgsjetII_EtaBin4->SetBinError(14,3.199522e-05);
   EnergyDist_qgsjetII_EtaBin4->SetBinError(15,1.670896e-05);
   EnergyDist_qgsjetII_EtaBin4->SetBinError(18,9.646923e-06);
   EnergyDist_qgsjetII_EtaBin4->SetBinError(31,9.646923e-06);
   EnergyDist_qgsjetII_EtaBin4->SetMinimum(1e-05);
   EnergyDist_qgsjetII_EtaBin4->SetMaximum(10);
   EnergyDist_qgsjetII_EtaBin4->SetEntries(3742);
   EnergyDist_qgsjetII_EtaBin4->SetStats(0);

   ci = TColor::GetColor("#00ff00");
   EnergyDist_qgsjetII_EtaBin4->SetLineColor(ci);
   EnergyDist_qgsjetII_EtaBin4->SetLineStyle(0);

   ci = TColor::GetColor("#00ff00");
   EnergyDist_qgsjetII_EtaBin4->SetMarkerColor(ci);
   EnergyDist_qgsjetII_EtaBin4->SetMarkerStyle(28);
   EnergyDist_qgsjetII_EtaBin4->SetMarkerSize(0.5);
   EnergyDist_qgsjetII_EtaBin4->GetXaxis()->SetTitle("Energy");
   EnergyDist_qgsjetII_EtaBin4->GetXaxis()->SetLabelFont(42);
   EnergyDist_qgsjetII_EtaBin4->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_qgsjetII_EtaBin4->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_qgsjetII_EtaBin4->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_qgsjetII_EtaBin4->GetXaxis()->SetTitleFont(42);
   EnergyDist_qgsjetII_EtaBin4->GetYaxis()->SetTitle("1/N");
   EnergyDist_qgsjetII_EtaBin4->GetYaxis()->SetLabelFont(42);
   EnergyDist_qgsjetII_EtaBin4->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_qgsjetII_EtaBin4->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_qgsjetII_EtaBin4->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_qgsjetII_EtaBin4->GetYaxis()->SetTitleFont(42);
   EnergyDist_qgsjetII_EtaBin4->GetZaxis()->SetLabelFont(42);
   EnergyDist_qgsjetII_EtaBin4->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_qgsjetII_EtaBin4->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_qgsjetII_EtaBin4->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_qgsjetII_EtaBin4->GetZaxis()->SetTitleFont(42);
   EnergyDist_qgsjetII_EtaBin4->Draw("same");
      tex = new TLatex(0.7,0.86,"3.853<|#eta|<4.204");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.68,0.6195462,1.12,0.8935428,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("EnergyDist_Data_EtaBin1","DATA","PL");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyDist_pythia8_Monash_EtaBin1","Pythia8 Monash","PL");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(24);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyDist_pythia8_TuneMBR_EtaBin1","Pythia8 MBR","PL");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#ff0000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(25);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyDist_epos_EtaBin1","EPOS-LHC","PL");

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#ff00ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(27);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyDist_qgsjetII_EtaBin1","QGSJET II","PL");

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#00ff00");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(28);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   leg->Draw();
      tex = new TLatex(0.75,0.15,"B = 0 T");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   cCaloTowerEnergy_Comp_MC_EtaBin4->Modified();
   cCaloTowerEnergy_Comp_MC_EtaBin4->cd();
   cCaloTowerEnergy_Comp_MC_EtaBin4->SetSelected(cCaloTowerEnergy_Comp_MC_EtaBin4);
}
