{
//=========Macro generated from canvas: cCaloTowerEnergy_Comp_MC_EtaBin6/cCaloTowerEnergy_Comp_MC_EtaBin6
//=========  (Wed Aug 17 13:00:44 2016) by ROOT version5.34/30
   TCanvas *cCaloTowerEnergy_Comp_MC_EtaBin6 = new TCanvas("cCaloTowerEnergy_Comp_MC_EtaBin6", "cCaloTowerEnergy_Comp_MC_EtaBin6",50,72,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cCaloTowerEnergy_Comp_MC_EtaBin6->Range(-42.85714,-5.9,314.2857,1.6);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetFillColor(0);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetBorderMode(0);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetBorderSize(2);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetLogy();
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetTickx(1);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetTicky(1);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetLeftMargin(0.12);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetRightMargin(0.04);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetTopMargin(0.08);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetBottomMargin(0.12);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetFrameFillStyle(0);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetFrameBorderMode(0);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetFrameFillStyle(0);
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetFrameBorderMode(0);
   
   TH1F *EnergyDist_Data_EtaBin6 = new TH1F("EnergyDist_Data_EtaBin6","EnergyDist_Data_EtaBin6",300,0,300);
   EnergyDist_Data_EtaBin6->SetBinContent(5,0.01617409);
   EnergyDist_Data_EtaBin6->SetBinContent(9,0.000291425);
   EnergyDist_Data_EtaBin6->SetBinContent(10,0.0005828501);
   EnergyDist_Data_EtaBin6->SetBinError(5,0.001535177);
   EnergyDist_Data_EtaBin6->SetBinError(9,0.0002060686);
   EnergyDist_Data_EtaBin6->SetBinError(10,0.000291425);
   EnergyDist_Data_EtaBin6->SetMinimum(1e-05);
   EnergyDist_Data_EtaBin6->SetMaximum(10);
   EnergyDist_Data_EtaBin6->SetEntries(117);
   EnergyDist_Data_EtaBin6->SetStats(0);
   EnergyDist_Data_EtaBin6->SetLineStyle(0);
   EnergyDist_Data_EtaBin6->SetMarkerStyle(20);
   EnergyDist_Data_EtaBin6->SetMarkerSize(0.5);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetTitle("Energy");
   EnergyDist_Data_EtaBin6->GetXaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetTitleOffset(0.9);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetTitle("1/N");
   EnergyDist_Data_EtaBin6->GetYaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin6->Draw("AXIS");
   TLatex *   tex = new TLatex(0.96,0.936,"0.06 nb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.892,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.82,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *EnergyDist_Data_EtaBin6__1 = new TH1F("EnergyDist_Data_EtaBin6__1","EnergyDist_Data_EtaBin6",300,0,300);
   EnergyDist_Data_EtaBin6__1->SetBinContent(5,0.01617409);
   EnergyDist_Data_EtaBin6__1->SetBinContent(9,0.000291425);
   EnergyDist_Data_EtaBin6__1->SetBinContent(10,0.0005828501);
   EnergyDist_Data_EtaBin6__1->SetBinError(5,0.001535177);
   EnergyDist_Data_EtaBin6__1->SetBinError(9,0.0002060686);
   EnergyDist_Data_EtaBin6__1->SetBinError(10,0.000291425);
   EnergyDist_Data_EtaBin6__1->SetMinimum(1e-05);
   EnergyDist_Data_EtaBin6__1->SetMaximum(10);
   EnergyDist_Data_EtaBin6__1->SetEntries(117);
   EnergyDist_Data_EtaBin6__1->SetDirectory(0);
   EnergyDist_Data_EtaBin6__1->SetStats(0);
   EnergyDist_Data_EtaBin6__1->SetLineStyle(0);
   EnergyDist_Data_EtaBin6__1->SetMarkerStyle(20);
   EnergyDist_Data_EtaBin6__1->SetMarkerSize(0.5);
   EnergyDist_Data_EtaBin6__1->GetXaxis()->SetTitle("Energy");
   EnergyDist_Data_EtaBin6__1->GetXaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin6__1->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin6__1->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin6__1->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin6__1->GetXaxis()->SetTitleOffset(0.9);
   EnergyDist_Data_EtaBin6__1->GetXaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin6__1->GetYaxis()->SetTitle("1/N");
   EnergyDist_Data_EtaBin6__1->GetYaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin6__1->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin6__1->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin6__1->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin6__1->GetYaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin6__1->GetZaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin6__1->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin6__1->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin6__1->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin6__1->GetZaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin6__1->Draw("sameaxis");
   
   TH1F *EnergyDist_Data_EtaBin6 = new TH1F("EnergyDist_Data_EtaBin6","EnergyDist_Data_EtaBin6",300,0,300);
   EnergyDist_Data_EtaBin6->SetBinContent(5,0.01617409);
   EnergyDist_Data_EtaBin6->SetBinContent(9,0.000291425);
   EnergyDist_Data_EtaBin6->SetBinContent(10,0.0005828501);
   EnergyDist_Data_EtaBin6->SetBinError(5,0.001535177);
   EnergyDist_Data_EtaBin6->SetBinError(9,0.0002060686);
   EnergyDist_Data_EtaBin6->SetBinError(10,0.000291425);
   EnergyDist_Data_EtaBin6->SetMinimum(1e-05);
   EnergyDist_Data_EtaBin6->SetMaximum(10);
   EnergyDist_Data_EtaBin6->SetEntries(117);
   EnergyDist_Data_EtaBin6->SetStats(0);
   EnergyDist_Data_EtaBin6->SetLineStyle(0);
   EnergyDist_Data_EtaBin6->SetMarkerStyle(20);
   EnergyDist_Data_EtaBin6->SetMarkerSize(0.5);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetTitle("Energy");
   EnergyDist_Data_EtaBin6->GetXaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetTitleOffset(0.9);
   EnergyDist_Data_EtaBin6->GetXaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetTitle("1/N");
   EnergyDist_Data_EtaBin6->GetYaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin6->GetYaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetLabelFont(42);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_Data_EtaBin6->GetZaxis()->SetTitleFont(42);
   EnergyDist_Data_EtaBin6->Draw("same");
   
   TH1F *EnergyDist_pythia8_Monash_EtaBin6 = new TH1F("EnergyDist_pythia8_Monash_EtaBin6","EnergyDist_pythia8_Monash_EtaBin6",300,0,300);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinContent(5,0.02183626);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinContent(9,0.0007940459);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinContent(10,0.0005923834);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinContent(13,1.890586e-05);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinContent(14,5.671757e-05);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinContent(15,1.26039e-05);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinContent(18,1.26039e-05);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinError(5,0.0003709597);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinError(9,7.073923e-05);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinError(10,6.109969e-05);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinError(13,1.09153e-05);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinError(14,1.890586e-05);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinError(15,8.912306e-06);
   EnergyDist_pythia8_Monash_EtaBin6->SetBinError(18,8.912306e-06);
   EnergyDist_pythia8_Monash_EtaBin6->SetMinimum(1e-05);
   EnergyDist_pythia8_Monash_EtaBin6->SetMaximum(10);
   EnergyDist_pythia8_Monash_EtaBin6->SetEntries(3701);
   EnergyDist_pythia8_Monash_EtaBin6->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   EnergyDist_pythia8_Monash_EtaBin6->SetLineColor(ci);
   EnergyDist_pythia8_Monash_EtaBin6->SetLineStyle(0);

   ci = TColor::GetColor("#0000ff");
   EnergyDist_pythia8_Monash_EtaBin6->SetMarkerColor(ci);
   EnergyDist_pythia8_Monash_EtaBin6->SetMarkerStyle(24);
   EnergyDist_pythia8_Monash_EtaBin6->SetMarkerSize(0.5);
   EnergyDist_pythia8_Monash_EtaBin6->GetXaxis()->SetTitle("Energy");
   EnergyDist_pythia8_Monash_EtaBin6->GetXaxis()->SetLabelFont(42);
   EnergyDist_pythia8_Monash_EtaBin6->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_Monash_EtaBin6->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin6->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin6->GetXaxis()->SetTitleFont(42);
   EnergyDist_pythia8_Monash_EtaBin6->GetYaxis()->SetTitle("1/N");
   EnergyDist_pythia8_Monash_EtaBin6->GetYaxis()->SetLabelFont(42);
   EnergyDist_pythia8_Monash_EtaBin6->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_Monash_EtaBin6->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin6->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin6->GetYaxis()->SetTitleFont(42);
   EnergyDist_pythia8_Monash_EtaBin6->GetZaxis()->SetLabelFont(42);
   EnergyDist_pythia8_Monash_EtaBin6->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_Monash_EtaBin6->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin6->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_Monash_EtaBin6->GetZaxis()->SetTitleFont(42);
   EnergyDist_pythia8_Monash_EtaBin6->Draw("same");
   
   TH1F *EnergyDist_pythia8_TuneMBR_EtaBin6 = new TH1F("EnergyDist_pythia8_TuneMBR_EtaBin6","EnergyDist_pythia8_TuneMBR_EtaBin6",300,0,300);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinContent(5,0.02563022);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinContent(9,0.001071926);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinContent(10,0.0006506215);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinContent(13,2.666482e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinContent(14,2.666482e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinContent(15,1.599889e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinError(5,0.0003697094);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinError(9,7.560781e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinError(10,5.890451e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinError(13,1.192487e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinError(14,1.192487e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetBinError(15,9.236964e-06);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetMinimum(1e-05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetMaximum(10);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetEntries(5142);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetLineColor(ci);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetLineStyle(0);

   ci = TColor::GetColor("#ff0000");
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetMarkerColor(ci);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetMarkerStyle(25);
   EnergyDist_pythia8_TuneMBR_EtaBin6->SetMarkerSize(0.5);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetXaxis()->SetTitle("Energy");
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetXaxis()->SetLabelFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetXaxis()->SetTitleFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetYaxis()->SetTitle("1/N");
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetYaxis()->SetLabelFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetYaxis()->SetTitleFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetZaxis()->SetLabelFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_pythia8_TuneMBR_EtaBin6->GetZaxis()->SetTitleFont(42);
   EnergyDist_pythia8_TuneMBR_EtaBin6->Draw("same");
   
   TH1F *EnergyDist_epos_EtaBin6 = new TH1F("EnergyDist_epos_EtaBin6","EnergyDist_epos_EtaBin6",300,0,300);
   EnergyDist_epos_EtaBin6->SetBinContent(5,0.02697476);
   EnergyDist_epos_EtaBin6->SetBinContent(9,0.001113244);
   EnergyDist_epos_EtaBin6->SetBinContent(10,0.0007921159);
   EnergyDist_epos_EtaBin6->SetBinContent(13,2.140854e-05);
   EnergyDist_epos_EtaBin6->SetBinContent(14,5.708944e-05);
   EnergyDist_epos_EtaBin6->SetBinContent(15,7.13618e-06);
   EnergyDist_epos_EtaBin6->SetBinContent(19,7.13618e-06);
   EnergyDist_epos_EtaBin6->SetBinError(5,0.0004387445);
   EnergyDist_epos_EtaBin6->SetBinError(9,8.913086e-05);
   EnergyDist_epos_EtaBin6->SetBinError(10,7.518432e-05);
   EnergyDist_epos_EtaBin6->SetBinError(13,1.236023e-05);
   EnergyDist_epos_EtaBin6->SetBinError(14,2.018416e-05);
   EnergyDist_epos_EtaBin6->SetBinError(15,7.13618e-06);
   EnergyDist_epos_EtaBin6->SetBinError(19,7.13618e-06);
   EnergyDist_epos_EtaBin6->SetMinimum(1e-05);
   EnergyDist_epos_EtaBin6->SetMaximum(10);
   EnergyDist_epos_EtaBin6->SetEntries(4060);
   EnergyDist_epos_EtaBin6->SetStats(0);

   ci = TColor::GetColor("#ff00ff");
   EnergyDist_epos_EtaBin6->SetLineColor(ci);
   EnergyDist_epos_EtaBin6->SetLineStyle(0);

   ci = TColor::GetColor("#ff00ff");
   EnergyDist_epos_EtaBin6->SetMarkerColor(ci);
   EnergyDist_epos_EtaBin6->SetMarkerStyle(27);
   EnergyDist_epos_EtaBin6->SetMarkerSize(0.5);
   EnergyDist_epos_EtaBin6->GetXaxis()->SetTitle("Energy");
   EnergyDist_epos_EtaBin6->GetXaxis()->SetLabelFont(42);
   EnergyDist_epos_EtaBin6->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_epos_EtaBin6->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_epos_EtaBin6->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_epos_EtaBin6->GetXaxis()->SetTitleFont(42);
   EnergyDist_epos_EtaBin6->GetYaxis()->SetTitle("1/N");
   EnergyDist_epos_EtaBin6->GetYaxis()->SetLabelFont(42);
   EnergyDist_epos_EtaBin6->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_epos_EtaBin6->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_epos_EtaBin6->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_epos_EtaBin6->GetYaxis()->SetTitleFont(42);
   EnergyDist_epos_EtaBin6->GetZaxis()->SetLabelFont(42);
   EnergyDist_epos_EtaBin6->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_epos_EtaBin6->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_epos_EtaBin6->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_epos_EtaBin6->GetZaxis()->SetTitleFont(42);
   EnergyDist_epos_EtaBin6->Draw("same");
   
   TH1F *EnergyDist_qgsjetII_EtaBin6 = new TH1F("EnergyDist_qgsjetII_EtaBin6","EnergyDist_qgsjetII_EtaBin6",300,0,300);
   EnergyDist_qgsjetII_EtaBin6->SetBinContent(5,0.03048428);
   EnergyDist_qgsjetII_EtaBin6->SetBinContent(9,0.001176925);
   EnergyDist_qgsjetII_EtaBin6->SetBinContent(10,0.0009550453);
   EnergyDist_qgsjetII_EtaBin6->SetBinContent(13,2.894077e-05);
   EnergyDist_qgsjetII_EtaBin6->SetBinContent(14,8.682231e-05);
   EnergyDist_qgsjetII_EtaBin6->SetBinContent(19,1.929385e-05);
   EnergyDist_qgsjetII_EtaBin6->SetBinError(5,0.0005422909);
   EnergyDist_qgsjetII_EtaBin6->SetBinError(9,0.0001065537);
   EnergyDist_qgsjetII_EtaBin6->SetBinError(10,9.598567e-05);
   EnergyDist_qgsjetII_EtaBin6->SetBinError(13,1.670896e-05);
   EnergyDist_qgsjetII_EtaBin6->SetBinError(14,2.894077e-05);
   EnergyDist_qgsjetII_EtaBin6->SetBinError(19,1.364281e-05);
   EnergyDist_qgsjetII_EtaBin6->SetMinimum(1e-05);
   EnergyDist_qgsjetII_EtaBin6->SetMaximum(10);
   EnergyDist_qgsjetII_EtaBin6->SetEntries(3395);
   EnergyDist_qgsjetII_EtaBin6->SetStats(0);

   ci = TColor::GetColor("#00ff00");
   EnergyDist_qgsjetII_EtaBin6->SetLineColor(ci);
   EnergyDist_qgsjetII_EtaBin6->SetLineStyle(0);

   ci = TColor::GetColor("#00ff00");
   EnergyDist_qgsjetII_EtaBin6->SetMarkerColor(ci);
   EnergyDist_qgsjetII_EtaBin6->SetMarkerStyle(28);
   EnergyDist_qgsjetII_EtaBin6->SetMarkerSize(0.5);
   EnergyDist_qgsjetII_EtaBin6->GetXaxis()->SetTitle("Energy");
   EnergyDist_qgsjetII_EtaBin6->GetXaxis()->SetLabelFont(42);
   EnergyDist_qgsjetII_EtaBin6->GetXaxis()->SetLabelOffset(0.007);
   EnergyDist_qgsjetII_EtaBin6->GetXaxis()->SetLabelSize(0.05);
   EnergyDist_qgsjetII_EtaBin6->GetXaxis()->SetTitleSize(0.05);
   EnergyDist_qgsjetII_EtaBin6->GetXaxis()->SetTitleFont(42);
   EnergyDist_qgsjetII_EtaBin6->GetYaxis()->SetTitle("1/N");
   EnergyDist_qgsjetII_EtaBin6->GetYaxis()->SetLabelFont(42);
   EnergyDist_qgsjetII_EtaBin6->GetYaxis()->SetLabelOffset(0.007);
   EnergyDist_qgsjetII_EtaBin6->GetYaxis()->SetLabelSize(0.05);
   EnergyDist_qgsjetII_EtaBin6->GetYaxis()->SetTitleSize(0.05);
   EnergyDist_qgsjetII_EtaBin6->GetYaxis()->SetTitleFont(42);
   EnergyDist_qgsjetII_EtaBin6->GetZaxis()->SetLabelFont(42);
   EnergyDist_qgsjetII_EtaBin6->GetZaxis()->SetLabelOffset(0.007);
   EnergyDist_qgsjetII_EtaBin6->GetZaxis()->SetLabelSize(0.05);
   EnergyDist_qgsjetII_EtaBin6->GetZaxis()->SetTitleSize(0.05);
   EnergyDist_qgsjetII_EtaBin6->GetZaxis()->SetTitleFont(42);
   EnergyDist_qgsjetII_EtaBin6->Draw("same");
      tex = new TLatex(0.7,0.86,"3.152<|#eta|<3.503");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.68,0.6195462,1.12,0.8935428,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("EnergyDist_Data_EtaBin1","DATA","PL");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyDist_pythia8_Monash_EtaBin1","Pythia8 Monash","PL");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(24);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyDist_pythia8_TuneMBR_EtaBin1","Pythia8 MBR","PL");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#ff0000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(25);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyDist_epos_EtaBin1","EPOS-LHC","PL");

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#ff00ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(27);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   entry=leg->AddEntry("EnergyDist_qgsjetII_EtaBin1","QGSJET II","PL");

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#00ff00");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(28);
   entry->SetMarkerSize(0.5);
   entry->SetTextFont(62);
   leg->Draw();
      tex = new TLatex(0.75,0.15,"B = 0 T");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   cCaloTowerEnergy_Comp_MC_EtaBin6->Modified();
   cCaloTowerEnergy_Comp_MC_EtaBin6->cd();
   cCaloTowerEnergy_Comp_MC_EtaBin6->SetSelected(cCaloTowerEnergy_Comp_MC_EtaBin6);
}
