{
//=========Macro generated from canvas: DataDetLOverMCDetL/DataDetLOverMCDetL
//=========  (Tue Aug 16 14:30:50 2016) by ROOT version5.34/30
   TCanvas *DataDetLOverMCDetL = new TCanvas("DataDetLOverMCDetL", "DataDetLOverMCDetL",58,77,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   DataDetLOverMCDetL->Range(2.659429,-0.335,6.76419,3.29);
   DataDetLOverMCDetL->SetFillColor(0);
   DataDetLOverMCDetL->SetBorderMode(0);
   DataDetLOverMCDetL->SetBorderSize(2);
   DataDetLOverMCDetL->SetTickx(1);
   DataDetLOverMCDetL->SetTicky(1);
   DataDetLOverMCDetL->SetLeftMargin(0.12);
   DataDetLOverMCDetL->SetRightMargin(0.04);
   DataDetLOverMCDetL->SetTopMargin(0.08);
   DataDetLOverMCDetL->SetBottomMargin(0.12);
   DataDetLOverMCDetL->SetFrameFillStyle(0);
   DataDetLOverMCDetL->SetFrameBorderMode(0);
   DataDetLOverMCDetL->SetFrameFillStyle(0);
   DataDetLOverMCDetL->SetFrameBorderMode(0);
   Double_t xAxis1[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataDetLOverpythia8_MonashDetL = new TH1F("DataDetLOverpythia8_MonashDetL","DataDetLOverpythia8_MonashDetL",7, xAxis1);
   DataDetLOverpythia8_MonashDetL->SetBinContent(1,1.264212);
   DataDetLOverpythia8_MonashDetL->SetBinContent(2,1.164237);
   DataDetLOverpythia8_MonashDetL->SetBinContent(3,1.158849);
   DataDetLOverpythia8_MonashDetL->SetBinContent(4,1.118885);
   DataDetLOverpythia8_MonashDetL->SetBinContent(5,1.136588);
   DataDetLOverpythia8_MonashDetL->SetBinContent(6,1.063054);
   DataDetLOverpythia8_MonashDetL->SetBinContent(7,0.9277743);
   DataDetLOverpythia8_MonashDetL->SetBinError(1,0.04106558);
   DataDetLOverpythia8_MonashDetL->SetBinError(2,0.03402916);
   DataDetLOverpythia8_MonashDetL->SetBinError(3,0.03248779);
   DataDetLOverpythia8_MonashDetL->SetBinError(4,0.03036965);
   DataDetLOverpythia8_MonashDetL->SetBinError(5,0.03208132);
   DataDetLOverpythia8_MonashDetL->SetBinError(6,0.02577655);
   DataDetLOverpythia8_MonashDetL->SetBinError(7,0.01958483);
   DataDetLOverpythia8_MonashDetL->SetMinimum(0.1);
   DataDetLOverpythia8_MonashDetL->SetMaximum(3);
   DataDetLOverpythia8_MonashDetL->SetEntries(7);
   DataDetLOverpythia8_MonashDetL->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#990099");
   DataDetLOverpythia8_MonashDetL->SetLineColor(ci);
   DataDetLOverpythia8_MonashDetL->SetLineStyle(2);
   DataDetLOverpythia8_MonashDetL->SetLineWidth(5);

   ci = TColor::GetColor("#990099");
   DataDetLOverpythia8_MonashDetL->SetMarkerColor(ci);
   DataDetLOverpythia8_MonashDetL->SetMarkerStyle(20);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetTitle("|#eta|");
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetNdivisions(511);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetLabelFont(42);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetLabelOffset(0.007);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetLabelSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetTitleSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetTitleOffset(0.9);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetTitleFont(42);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetLabelFont(42);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetLabelOffset(0.007);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetLabelSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetTitleSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetTitleFont(42);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetLabelFont(42);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetLabelOffset(0.007);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetLabelSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetTitleSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetTitleFont(42);
   DataDetLOverpythia8_MonashDetL->Draw("AXIS");
   TLatex *   tex = new TLatex(0.96,0.936,"0.06 nb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.892,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1578,0.82,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis2[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataDetLOverpythia8_MonashDetL__1 = new TH1F("DataDetLOverpythia8_MonashDetL__1","DataDetLOverpythia8_MonashDetL",7, xAxis2);
   DataDetLOverpythia8_MonashDetL__1->SetBinContent(1,1.264212);
   DataDetLOverpythia8_MonashDetL__1->SetBinContent(2,1.164237);
   DataDetLOverpythia8_MonashDetL__1->SetBinContent(3,1.158849);
   DataDetLOverpythia8_MonashDetL__1->SetBinContent(4,1.118885);
   DataDetLOverpythia8_MonashDetL__1->SetBinContent(5,1.136588);
   DataDetLOverpythia8_MonashDetL__1->SetBinContent(6,1.063054);
   DataDetLOverpythia8_MonashDetL__1->SetBinContent(7,0.9277743);
   DataDetLOverpythia8_MonashDetL__1->SetBinError(1,0.04106558);
   DataDetLOverpythia8_MonashDetL__1->SetBinError(2,0.03402916);
   DataDetLOverpythia8_MonashDetL__1->SetBinError(3,0.03248779);
   DataDetLOverpythia8_MonashDetL__1->SetBinError(4,0.03036965);
   DataDetLOverpythia8_MonashDetL__1->SetBinError(5,0.03208132);
   DataDetLOverpythia8_MonashDetL__1->SetBinError(6,0.02577655);
   DataDetLOverpythia8_MonashDetL__1->SetBinError(7,0.01958483);
   DataDetLOverpythia8_MonashDetL__1->SetMinimum(0.1);
   DataDetLOverpythia8_MonashDetL__1->SetMaximum(3);
   DataDetLOverpythia8_MonashDetL__1->SetEntries(7);
   DataDetLOverpythia8_MonashDetL__1->SetDirectory(0);
   DataDetLOverpythia8_MonashDetL__1->SetStats(0);

   ci = TColor::GetColor("#990099");
   DataDetLOverpythia8_MonashDetL__1->SetLineColor(ci);
   DataDetLOverpythia8_MonashDetL__1->SetLineStyle(2);
   DataDetLOverpythia8_MonashDetL__1->SetLineWidth(5);

   ci = TColor::GetColor("#990099");
   DataDetLOverpythia8_MonashDetL__1->SetMarkerColor(ci);
   DataDetLOverpythia8_MonashDetL__1->SetMarkerStyle(20);
   DataDetLOverpythia8_MonashDetL__1->GetXaxis()->SetTitle("|#eta|");
   DataDetLOverpythia8_MonashDetL__1->GetXaxis()->SetNdivisions(511);
   DataDetLOverpythia8_MonashDetL__1->GetXaxis()->SetLabelFont(42);
   DataDetLOverpythia8_MonashDetL__1->GetXaxis()->SetLabelOffset(0.007);
   DataDetLOverpythia8_MonashDetL__1->GetXaxis()->SetLabelSize(0.05);
   DataDetLOverpythia8_MonashDetL__1->GetXaxis()->SetTitleSize(0.05);
   DataDetLOverpythia8_MonashDetL__1->GetXaxis()->SetTitleOffset(0.9);
   DataDetLOverpythia8_MonashDetL__1->GetXaxis()->SetTitleFont(42);
   DataDetLOverpythia8_MonashDetL__1->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataDetLOverpythia8_MonashDetL__1->GetYaxis()->SetLabelFont(42);
   DataDetLOverpythia8_MonashDetL__1->GetYaxis()->SetLabelOffset(0.007);
   DataDetLOverpythia8_MonashDetL__1->GetYaxis()->SetLabelSize(0.05);
   DataDetLOverpythia8_MonashDetL__1->GetYaxis()->SetTitleSize(0.05);
   DataDetLOverpythia8_MonashDetL__1->GetYaxis()->SetTitleFont(42);
   DataDetLOverpythia8_MonashDetL__1->GetZaxis()->SetLabelFont(42);
   DataDetLOverpythia8_MonashDetL__1->GetZaxis()->SetLabelOffset(0.007);
   DataDetLOverpythia8_MonashDetL__1->GetZaxis()->SetLabelSize(0.05);
   DataDetLOverpythia8_MonashDetL__1->GetZaxis()->SetTitleSize(0.05);
   DataDetLOverpythia8_MonashDetL__1->GetZaxis()->SetTitleFont(42);
   DataDetLOverpythia8_MonashDetL__1->Draw("sameaxis");
   Double_t xAxis3[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataDetLOverDataDetL = new TH1F("DataDetLOverDataDetL","DataDetLOverDataDetL",7, xAxis3);
   DataDetLOverDataDetL->SetBinContent(1,1.095307);
   DataDetLOverDataDetL->SetBinContent(2,0.9735463);
   DataDetLOverDataDetL->SetBinContent(3,0.9686545);
   DataDetLOverDataDetL->SetBinContent(4,0.9235725);
   DataDetLOverDataDetL->SetBinContent(5,0.9310705);
   DataDetLOverDataDetL->SetBinContent(6,0.8569342);
   DataDetLOverDataDetL->SetBinContent(7,0.7804156);
   DataDetLOverDataDetL->SetBinError(1,0.03130782);
   DataDetLOverDataDetL->SetBinError(2,0.02392623);
   DataDetLOverDataDetL->SetBinError(3,0.02281125);
   DataDetLOverDataDetL->SetBinError(4,0.02062758);
   DataDetLOverDataDetL->SetBinError(5,0.02151281);
   DataDetLOverDataDetL->SetBinError(6,0.01640068);
   DataDetLOverDataDetL->SetBinError(7,0.01317236);
   DataDetLOverDataDetL->SetMinimum(0.1);
   DataDetLOverDataDetL->SetMaximum(3);
   DataDetLOverDataDetL->SetEntries(7);
   DataDetLOverDataDetL->SetStats(0);

   ci = TColor::GetColor("#006633");
   DataDetLOverDataDetL->SetLineColor(ci);
   DataDetLOverDataDetL->SetLineWidth(5);

   ci = TColor::GetColor("#006633");
   DataDetLOverDataDetL->SetMarkerColor(ci);
   DataDetLOverDataDetL->SetMarkerStyle(20);
   DataDetLOverDataDetL->GetXaxis()->SetTitle("|#eta|");
   DataDetLOverDataDetL->GetXaxis()->SetNdivisions(511);
   DataDetLOverDataDetL->GetXaxis()->SetLabelFont(42);
   DataDetLOverDataDetL->GetXaxis()->SetLabelOffset(0.007);
   DataDetLOverDataDetL->GetXaxis()->SetLabelSize(0.05);
   DataDetLOverDataDetL->GetXaxis()->SetTitleSize(0.05);
   DataDetLOverDataDetL->GetXaxis()->SetTitleFont(42);
   DataDetLOverDataDetL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataDetLOverDataDetL->GetYaxis()->SetLabelFont(42);
   DataDetLOverDataDetL->GetYaxis()->SetLabelOffset(0.007);
   DataDetLOverDataDetL->GetYaxis()->SetLabelSize(0.05);
   DataDetLOverDataDetL->GetYaxis()->SetTitleSize(0.05);
   DataDetLOverDataDetL->GetYaxis()->SetTitleFont(42);
   DataDetLOverDataDetL->GetZaxis()->SetLabelFont(42);
   DataDetLOverDataDetL->GetZaxis()->SetLabelOffset(0.007);
   DataDetLOverDataDetL->GetZaxis()->SetLabelSize(0.05);
   DataDetLOverDataDetL->GetZaxis()->SetTitleSize(0.05);
   DataDetLOverDataDetL->GetZaxis()->SetTitleFont(42);
   DataDetLOverDataDetL->Draw("same hist");
   Double_t xAxis4[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataDetLOverpythia8_MonashDetL = new TH1F("DataDetLOverpythia8_MonashDetL","DataDetLOverpythia8_MonashDetL",7, xAxis4);
   DataDetLOverpythia8_MonashDetL->SetBinContent(1,1.264212);
   DataDetLOverpythia8_MonashDetL->SetBinContent(2,1.164237);
   DataDetLOverpythia8_MonashDetL->SetBinContent(3,1.158849);
   DataDetLOverpythia8_MonashDetL->SetBinContent(4,1.118885);
   DataDetLOverpythia8_MonashDetL->SetBinContent(5,1.136588);
   DataDetLOverpythia8_MonashDetL->SetBinContent(6,1.063054);
   DataDetLOverpythia8_MonashDetL->SetBinContent(7,0.9277743);
   DataDetLOverpythia8_MonashDetL->SetBinError(1,0.04106558);
   DataDetLOverpythia8_MonashDetL->SetBinError(2,0.03402916);
   DataDetLOverpythia8_MonashDetL->SetBinError(3,0.03248779);
   DataDetLOverpythia8_MonashDetL->SetBinError(4,0.03036965);
   DataDetLOverpythia8_MonashDetL->SetBinError(5,0.03208132);
   DataDetLOverpythia8_MonashDetL->SetBinError(6,0.02577655);
   DataDetLOverpythia8_MonashDetL->SetBinError(7,0.01958483);
   DataDetLOverpythia8_MonashDetL->SetMinimum(0.1);
   DataDetLOverpythia8_MonashDetL->SetMaximum(3);
   DataDetLOverpythia8_MonashDetL->SetEntries(7);
   DataDetLOverpythia8_MonashDetL->SetStats(0);

   ci = TColor::GetColor("#990099");
   DataDetLOverpythia8_MonashDetL->SetLineColor(ci);
   DataDetLOverpythia8_MonashDetL->SetLineStyle(2);
   DataDetLOverpythia8_MonashDetL->SetLineWidth(5);

   ci = TColor::GetColor("#990099");
   DataDetLOverpythia8_MonashDetL->SetMarkerColor(ci);
   DataDetLOverpythia8_MonashDetL->SetMarkerStyle(20);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetTitle("|#eta|");
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetNdivisions(511);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetLabelFont(42);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetLabelOffset(0.007);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetLabelSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetTitleSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetTitleOffset(0.9);
   DataDetLOverpythia8_MonashDetL->GetXaxis()->SetTitleFont(42);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetLabelFont(42);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetLabelOffset(0.007);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetLabelSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetTitleSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetYaxis()->SetTitleFont(42);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetLabelFont(42);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetLabelOffset(0.007);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetLabelSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetTitleSize(0.05);
   DataDetLOverpythia8_MonashDetL->GetZaxis()->SetTitleFont(42);
   DataDetLOverpythia8_MonashDetL->Draw("same hist");
   Double_t xAxis5[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataDetLOverherwigppDetL = new TH1F("DataDetLOverherwigppDetL","DataDetLOverherwigppDetL",7, xAxis5);
   DataDetLOverherwigppDetL->SetBinContent(1,1.646472);
   DataDetLOverherwigppDetL->SetBinContent(2,1.471582);
   DataDetLOverherwigppDetL->SetBinContent(3,1.451173);
   DataDetLOverherwigppDetL->SetBinContent(4,1.40911);
   DataDetLOverherwigppDetL->SetBinContent(5,1.428258);
   DataDetLOverherwigppDetL->SetBinContent(6,1.325361);
   DataDetLOverherwigppDetL->SetBinContent(7,1.144023);
   DataDetLOverherwigppDetL->SetBinError(1,0.06561282);
   DataDetLOverherwigppDetL->SetBinError(2,0.05215072);
   DataDetLOverherwigppDetL->SetBinError(3,0.0489553);
   DataDetLOverherwigppDetL->SetBinError(4,0.04643339);
   DataDetLOverherwigppDetL->SetBinError(5,0.04874133);
   DataDetLOverherwigppDetL->SetBinError(6,0.03896176);
   DataDetLOverherwigppDetL->SetBinError(7,0.02960906);
   DataDetLOverherwigppDetL->SetMinimum(0.1);
   DataDetLOverherwigppDetL->SetMaximum(3);
   DataDetLOverherwigppDetL->SetEntries(7);
   DataDetLOverherwigppDetL->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   DataDetLOverherwigppDetL->SetLineColor(ci);
   DataDetLOverherwigppDetL->SetLineStyle(4);
   DataDetLOverherwigppDetL->SetLineWidth(5);

   ci = TColor::GetColor("#0000ff");
   DataDetLOverherwigppDetL->SetMarkerColor(ci);
   DataDetLOverherwigppDetL->SetMarkerStyle(20);
   DataDetLOverherwigppDetL->GetXaxis()->SetTitle("|#eta|");
   DataDetLOverherwigppDetL->GetXaxis()->SetLabelFont(42);
   DataDetLOverherwigppDetL->GetXaxis()->SetLabelOffset(0.007);
   DataDetLOverherwigppDetL->GetXaxis()->SetLabelSize(0.05);
   DataDetLOverherwigppDetL->GetXaxis()->SetTitleSize(0.05);
   DataDetLOverherwigppDetL->GetXaxis()->SetTitleFont(42);
   DataDetLOverherwigppDetL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataDetLOverherwigppDetL->GetYaxis()->SetLabelFont(42);
   DataDetLOverherwigppDetL->GetYaxis()->SetLabelOffset(0.007);
   DataDetLOverherwigppDetL->GetYaxis()->SetLabelSize(0.05);
   DataDetLOverherwigppDetL->GetYaxis()->SetTitleSize(0.05);
   DataDetLOverherwigppDetL->GetYaxis()->SetTitleFont(42);
   DataDetLOverherwigppDetL->GetZaxis()->SetLabelFont(42);
   DataDetLOverherwigppDetL->GetZaxis()->SetLabelOffset(0.007);
   DataDetLOverherwigppDetL->GetZaxis()->SetLabelSize(0.05);
   DataDetLOverherwigppDetL->GetZaxis()->SetTitleSize(0.05);
   DataDetLOverherwigppDetL->GetZaxis()->SetTitleFont(42);
   DataDetLOverherwigppDetL->Draw("same hist");
   Double_t xAxis6[8] = {3.152, 3.503, 3.853, 4.204, 4.552, 4.903, 5.205, 6.6}; 
   
   TH1F *DataDetLOvereposDetL = new TH1F("DataDetLOvereposDetL","DataDetLOvereposDetL",7, xAxis6);
   DataDetLOvereposDetL->SetBinContent(1,1.330191);
   DataDetLOvereposDetL->SetBinContent(2,1.177423);
   DataDetLOvereposDetL->SetBinContent(3,1.156061);
   DataDetLOvereposDetL->SetBinContent(4,1.116406);
   DataDetLOvereposDetL->SetBinContent(5,1.091811);
   DataDetLOvereposDetL->SetBinContent(6,1.024983);
   DataDetLOvereposDetL->SetBinContent(7,0.8935192);
   DataDetLOvereposDetL->SetBinError(1,0.04458577);
   DataDetLOvereposDetL->SetBinError(2,0.0344342);
   DataDetLOvereposDetL->SetBinError(3,0.03201856);
   DataDetLOvereposDetL->SetBinError(4,0.02993304);
   DataDetLOvereposDetL->SetBinError(5,0.02933132);
   DataDetLOvereposDetL->SetBinError(6,0.02358806);
   DataDetLOvereposDetL->SetBinError(7,0.01779187);
   DataDetLOvereposDetL->SetMinimum(0.1);
   DataDetLOvereposDetL->SetMaximum(3);
   DataDetLOvereposDetL->SetEntries(7);
   DataDetLOvereposDetL->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   DataDetLOvereposDetL->SetLineColor(ci);
   DataDetLOvereposDetL->SetLineStyle(5);
   DataDetLOvereposDetL->SetLineWidth(5);

   ci = TColor::GetColor("#ff0000");
   DataDetLOvereposDetL->SetMarkerColor(ci);
   DataDetLOvereposDetL->SetMarkerStyle(20);
   DataDetLOvereposDetL->GetXaxis()->SetTitle("|#eta|");
   DataDetLOvereposDetL->GetXaxis()->SetLabelFont(42);
   DataDetLOvereposDetL->GetXaxis()->SetLabelOffset(0.007);
   DataDetLOvereposDetL->GetXaxis()->SetLabelSize(0.05);
   DataDetLOvereposDetL->GetXaxis()->SetTitleSize(0.05);
   DataDetLOvereposDetL->GetXaxis()->SetTitleFont(42);
   DataDetLOvereposDetL->GetYaxis()->SetTitle("#frac{dE}{d|#eta|}[DATA] / #frac{dE}{d|#eta|}[MC]");
   DataDetLOvereposDetL->GetYaxis()->SetLabelFont(42);
   DataDetLOvereposDetL->GetYaxis()->SetLabelOffset(0.007);
   DataDetLOvereposDetL->GetYaxis()->SetLabelSize(0.05);
   DataDetLOvereposDetL->GetYaxis()->SetTitleSize(0.05);
   DataDetLOvereposDetL->GetYaxis()->SetTitleFont(42);
   DataDetLOvereposDetL->GetZaxis()->SetLabelFont(42);
   DataDetLOvereposDetL->GetZaxis()->SetLabelOffset(0.007);
   DataDetLOvereposDetL->GetZaxis()->SetLabelSize(0.05);
   DataDetLOvereposDetL->GetZaxis()->SetTitleSize(0.05);
   DataDetLOvereposDetL->GetZaxis()->SetTitleFont(42);
   DataDetLOvereposDetL->Draw("same hist");
      tex = new TLatex(0.75,0.2,"CaloTower");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.75,0.15,"B = 0 T");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6444724,0.6311189,0.8643216,0.9055944,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("DataDetLOverDataDetL","Pythia8 Monash","L");

   ci = TColor::GetColor("#006633");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("DataDetLOverpythia8_MonashDetL","Pythia8 MBR","L");

   ci = TColor::GetColor("#990099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("DataDetLOverherwigppDetL","EPOS-LHC","L");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(4);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("DataDetLOvereposDetL","QGSJET II","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(5);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   TLine *line = new TLine(3.139,1,6.6,1);
   line->Draw();
   DataDetLOverMCDetL->Modified();
   DataDetLOverMCDetL->cd();
   DataDetLOverMCDetL->SetSelected(DataDetLOverMCDetL);
}
